# Generated by Django 5.2.9 on 2026-06-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='emails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Редактировано'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='Тема'),
        ),
    ]
