# Generated by Django 5.2.9 on 2026-03-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_user_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
