# Generated by Django 5.2.9 on 2026-04-11 10:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default=api.models.generate_random_string, max_length=11, unique=True),
        ),
    ]
