# Generated by Django 5.2.9 on 2026-04-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cart_cart_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название (напр. DHL)')),
                ('description', models.TextField(blank=True, verbose_name='Описание (напр. 2-3 рабочих дня)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon_delivery', verbose_name='Загрузить иконку')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Вариант доставки',
                'verbose_name_plural': 'Варианты доставки',
                'ordering': ['order'],
            },
        ),
    ]
