# Generated by Django 5.2.9 on 2026-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deliveryoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='is_pickup',
            field=models.BooleanField(default=False, verbose_name='Это самовывоз?'),
        ),
    ]
