# Generated by Django 5.2.9 on 2026-04-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_deliveryoption_is_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'для мужчин'), ('F', 'для женщин'), ('U', 'унисекс')], default='U', max_length=2, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(choices=[(True, 'в наличии'), (False, 'нет в наличии')], default=1, verbose_name='Наличие'),
        ),
    ]
