# Generated by Django 5.2.9 on 2026-04-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
