# Generated by Django 5.2.9 on 2026-04-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код цвета (HEX)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='api.color', verbose_name='Цвет'),
        ),
    ]
