# Generated by Django 5.2.9 on 2026-04-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_color_slug_color_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код цвета (HEX)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='goods', to='api.color', verbose_name='Цвет'),
        ),
    ]
