# Generated by Django 5.2.9 on 2026-04-26 16:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_color_color_code_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Выберите цвет'),
        ),
    ]
