# Generated by Django 5.2.9 on 2026-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePresets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Ярлык для диапазона')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная цена')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная цена')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Диапазоны цены',
                'verbose_name_plural': 'Диапазоны цены',
                'ordering': ['order'],
            },
        ),
    ]
