# Generated by Django 5.2.9 on 2026-06-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_product_options_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название (напр. DHL)'),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название (напр. DHL)'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_ru',
            field=models.TextField(null=True),
        ),
    ]
