# Generated by Django 5.2.9 on 2026-06-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_color_name_en_color_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='phone',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='house',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='zip',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, default='Россия', max_length=50, null=True),
        ),
    ]
