# Generated by Django 5.2.9 on 2026-06-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_customeraddress_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='zip',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
