# Generated by Django 5.2.9 on 2026-08-02 16:18

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_currencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='city_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='city_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='region_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='region_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state_en',
            field=models.CharField(blank=True, default='Россия', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state_ru',
            field=models.CharField(blank=True, default='Россия', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='street_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='street_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=api.models.get_default_brand, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='api.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default=api.models.get_default_color, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='goods', to='api.color', verbose_name='Цвет'),
        ),
    ]
