/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchSearchRouteImport } from './routes/_search/search'
import { Route as LangMainLayoutRouteImport } from './routes/$lang/_mainLayout'
import { Route as LangMainLayoutIndexRouteImport } from './routes/$lang/_mainLayout.index'
import { Route as LangPaymentResultSuccessRouteImport } from './routes/$lang/_paymentResult/success'
import { Route as LangMainLayoutAuthenticatedRouteImport } from './routes/$lang/_mainLayout/_authenticated'
import { Route as LangAuthRegisterRouteImport } from './routes/$lang/_auth/register'
import { Route as LangAuthPasswordResetRequestRouteImport } from './routes/$lang/_auth/passwordResetRequest'
import { Route as LangAuthLoginRouteImport } from './routes/$lang/_auth/login'
import { Route as LangMainLayoutProductsProductSlugRouteImport } from './routes/$lang/_mainLayout/products/$productSlug'
import { Route as LangMainLayoutNewsNewsIndexRouteImport } from './routes/$lang/_mainLayout/news/newsIndex'
import { Route as LangMainLayoutNewsNewsSlugRouteImport } from './routes/$lang/_mainLayout/news/$newsSlug'
import { Route as LangMainLayoutCategoriesCategoryIdRouteImport } from './routes/$lang/_mainLayout/categories/$categoryId'
import { Route as LangMainLayoutFilterProductsRouteImport } from './routes/$lang/_mainLayout/_filter/products'
import { Route as LangMainLayoutAuthenticatedUsers_tanstackRouteImport } from './routes/$lang/_mainLayout/_authenticated/users_tanstack'
import { Route as LangAuthVerify_email_resetTokenRouteImport } from './routes/$lang/_auth/verify_email_reset/$token'
import { Route as LangAuthPasswordResetTokenRouteImport } from './routes/$lang/_auth/password-reset/$token'

const TestTestLazyRouteImport = createFileRoute('/_test/test')()
const LangPaymentResultFailedLazyRouteImport = createFileRoute(
  '/$lang/_paymentResult/failed',
)()
const LangMainLayoutAuthenticatedUsersLazyRouteImport = createFileRoute(
  '/$lang/_mainLayout/_authenticated/users',
)()
const LangMainLayoutAuthenticatedProfileLazyRouteImport = createFileRoute(
  '/$lang/_mainLayout/_authenticated/profile',
)()
const LangMainLayoutAuthenticatedCheckoutLazyRouteImport = createFileRoute(
  '/$lang/_mainLayout/_authenticated/checkout',
)()
const LangMainLayoutAuthenticatedCartIndexLazyRouteImport = createFileRoute(
  '/$lang/_mainLayout/_authenticated/cart/',
)()
const LangMainLayoutAuthenticatedCartCartcodeLazyRouteImport = createFileRoute(
  '/$lang/_mainLayout/_authenticated/cart/$cartcode',
)()
const LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRouteImport =
  createFileRoute('/$lang/_mainLayout/_authenticated/_CloudPayment/payment')()

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestLazyRoute = TestTestLazyRouteImport.update({
  id: '/_test/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_test/test.lazy').then((d) => d.Route))
const SearchSearchRoute = SearchSearchRouteImport.update({
  id: '/_search/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_search/search.lazy').then((d) => d.Route),
)
const LangMainLayoutRoute = LangMainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => LangRoute,
} as any)
const LangMainLayoutIndexRoute = LangMainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangMainLayoutRoute,
} as any).lazy(() =>
  import('./routes/$lang/_mainLayout.index.lazy').then((d) => d.Route),
)
const LangPaymentResultFailedLazyRoute =
  LangPaymentResultFailedLazyRouteImport.update({
    id: '/_paymentResult/failed',
    path: '/failed',
    getParentRoute: () => LangRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_paymentResult/failed.lazy').then((d) => d.Route),
  )
const LangPaymentResultSuccessRoute =
  LangPaymentResultSuccessRouteImport.update({
    id: '/_paymentResult/success',
    path: '/success',
    getParentRoute: () => LangRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_paymentResult/success.lazy').then((d) => d.Route),
  )
const LangMainLayoutAuthenticatedRoute =
  LangMainLayoutAuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => LangMainLayoutRoute,
  } as any)
const LangAuthRegisterRoute = LangAuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthPasswordResetRequestRoute =
  LangAuthPasswordResetRequestRouteImport.update({
    id: '/_auth/passwordResetRequest',
    path: '/passwordResetRequest',
    getParentRoute: () => LangRoute,
  } as any)
const LangAuthLoginRoute = LangAuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => LangRoute,
} as any)
const LangMainLayoutAuthenticatedUsersLazyRoute =
  LangMainLayoutAuthenticatedUsersLazyRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => LangMainLayoutAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/_authenticated/users.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutAuthenticatedProfileLazyRoute =
  LangMainLayoutAuthenticatedProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LangMainLayoutAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/_authenticated/profile.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutAuthenticatedCheckoutLazyRoute =
  LangMainLayoutAuthenticatedCheckoutLazyRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => LangMainLayoutAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/_authenticated/checkout.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutProductsProductSlugRoute =
  LangMainLayoutProductsProductSlugRouteImport.update({
    id: '/products/$productSlug',
    path: '/products/$productSlug',
    getParentRoute: () => LangMainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/products/$productSlug.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutNewsNewsIndexRoute =
  LangMainLayoutNewsNewsIndexRouteImport.update({
    id: '/news/newsIndex',
    path: '/news/newsIndex',
    getParentRoute: () => LangMainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/news/newsIndex.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutNewsNewsSlugRoute =
  LangMainLayoutNewsNewsSlugRouteImport.update({
    id: '/news/$newsSlug',
    path: '/news/$newsSlug',
    getParentRoute: () => LangMainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/news/$newsSlug.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutCategoriesCategoryIdRoute =
  LangMainLayoutCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => LangMainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/categories/$categoryId.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutFilterProductsRoute =
  LangMainLayoutFilterProductsRouteImport.update({
    id: '/_filter/products',
    path: '/products',
    getParentRoute: () => LangMainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/_filter/products.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutAuthenticatedUsers_tanstackRoute =
  LangMainLayoutAuthenticatedUsers_tanstackRouteImport.update({
    id: '/users_tanstack',
    path: '/users_tanstack',
    getParentRoute: () => LangMainLayoutAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/_authenticated/users_tanstack.lazy').then(
      (d) => d.Route,
    ),
  )
const LangAuthVerify_email_resetTokenRoute =
  LangAuthVerify_email_resetTokenRouteImport.update({
    id: '/_auth/verify_email_reset/$token',
    path: '/verify_email_reset/$token',
    getParentRoute: () => LangRoute,
  } as any)
const LangAuthPasswordResetTokenRoute =
  LangAuthPasswordResetTokenRouteImport.update({
    id: '/_auth/password-reset/$token',
    path: '/password-reset/$token',
    getParentRoute: () => LangRoute,
  } as any)
const LangMainLayoutAuthenticatedCartIndexLazyRoute =
  LangMainLayoutAuthenticatedCartIndexLazyRouteImport.update({
    id: '/cart/',
    path: '/cart/',
    getParentRoute: () => LangMainLayoutAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/_authenticated/cart/index.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutAuthenticatedCartCartcodeLazyRoute =
  LangMainLayoutAuthenticatedCartCartcodeLazyRouteImport.update({
    id: '/cart/$cartcode',
    path: '/cart/$cartcode',
    getParentRoute: () => LangMainLayoutAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/_authenticated/cart/$cartcode.lazy').then(
      (d) => d.Route,
    ),
  )
const LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRoute =
  LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRouteImport.update({
    id: '/_CloudPayment/payment',
    path: '/payment',
    getParentRoute: () => LangMainLayoutAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/$lang/_mainLayout/_authenticated/_CloudPayment/payment.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangMainLayoutAuthenticatedRouteWithChildren
  '/search': typeof SearchSearchRoute
  '/test': typeof TestTestLazyRoute
  '/$lang/login': typeof LangAuthLoginRoute
  '/$lang/passwordResetRequest': typeof LangAuthPasswordResetRequestRoute
  '/$lang/register': typeof LangAuthRegisterRoute
  '/$lang/success': typeof LangPaymentResultSuccessRoute
  '/$lang/failed': typeof LangPaymentResultFailedLazyRoute
  '/$lang/': typeof LangMainLayoutIndexRoute
  '/$lang/password-reset/$token': typeof LangAuthPasswordResetTokenRoute
  '/$lang/verify_email_reset/$token': typeof LangAuthVerify_email_resetTokenRoute
  '/$lang/users_tanstack': typeof LangMainLayoutAuthenticatedUsers_tanstackRoute
  '/$lang/products': typeof LangMainLayoutFilterProductsRoute
  '/$lang/categories/$categoryId': typeof LangMainLayoutCategoriesCategoryIdRoute
  '/$lang/news/$newsSlug': typeof LangMainLayoutNewsNewsSlugRoute
  '/$lang/news/newsIndex': typeof LangMainLayoutNewsNewsIndexRoute
  '/$lang/products/$productSlug': typeof LangMainLayoutProductsProductSlugRoute
  '/$lang/checkout': typeof LangMainLayoutAuthenticatedCheckoutLazyRoute
  '/$lang/profile': typeof LangMainLayoutAuthenticatedProfileLazyRoute
  '/$lang/users': typeof LangMainLayoutAuthenticatedUsersLazyRoute
  '/$lang/payment': typeof LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRoute
  '/$lang/cart/$cartcode': typeof LangMainLayoutAuthenticatedCartCartcodeLazyRoute
  '/$lang/cart': typeof LangMainLayoutAuthenticatedCartIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangMainLayoutIndexRoute
  '/search': typeof SearchSearchRoute
  '/test': typeof TestTestLazyRoute
  '/$lang/login': typeof LangAuthLoginRoute
  '/$lang/passwordResetRequest': typeof LangAuthPasswordResetRequestRoute
  '/$lang/register': typeof LangAuthRegisterRoute
  '/$lang/success': typeof LangPaymentResultSuccessRoute
  '/$lang/failed': typeof LangPaymentResultFailedLazyRoute
  '/$lang/password-reset/$token': typeof LangAuthPasswordResetTokenRoute
  '/$lang/verify_email_reset/$token': typeof LangAuthVerify_email_resetTokenRoute
  '/$lang/users_tanstack': typeof LangMainLayoutAuthenticatedUsers_tanstackRoute
  '/$lang/products': typeof LangMainLayoutFilterProductsRoute
  '/$lang/categories/$categoryId': typeof LangMainLayoutCategoriesCategoryIdRoute
  '/$lang/news/$newsSlug': typeof LangMainLayoutNewsNewsSlugRoute
  '/$lang/news/newsIndex': typeof LangMainLayoutNewsNewsIndexRoute
  '/$lang/products/$productSlug': typeof LangMainLayoutProductsProductSlugRoute
  '/$lang/checkout': typeof LangMainLayoutAuthenticatedCheckoutLazyRoute
  '/$lang/profile': typeof LangMainLayoutAuthenticatedProfileLazyRoute
  '/$lang/users': typeof LangMainLayoutAuthenticatedUsersLazyRoute
  '/$lang/payment': typeof LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRoute
  '/$lang/cart/$cartcode': typeof LangMainLayoutAuthenticatedCartCartcodeLazyRoute
  '/$lang/cart': typeof LangMainLayoutAuthenticatedCartIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/_mainLayout': typeof LangMainLayoutRouteWithChildren
  '/_search/search': typeof SearchSearchRoute
  '/_test/test': typeof TestTestLazyRoute
  '/$lang/_auth/login': typeof LangAuthLoginRoute
  '/$lang/_auth/passwordResetRequest': typeof LangAuthPasswordResetRequestRoute
  '/$lang/_auth/register': typeof LangAuthRegisterRoute
  '/$lang/_mainLayout/_authenticated': typeof LangMainLayoutAuthenticatedRouteWithChildren
  '/$lang/_paymentResult/success': typeof LangPaymentResultSuccessRoute
  '/$lang/_paymentResult/failed': typeof LangPaymentResultFailedLazyRoute
  '/$lang/_mainLayout/': typeof LangMainLayoutIndexRoute
  '/$lang/_auth/password-reset/$token': typeof LangAuthPasswordResetTokenRoute
  '/$lang/_auth/verify_email_reset/$token': typeof LangAuthVerify_email_resetTokenRoute
  '/$lang/_mainLayout/_authenticated/users_tanstack': typeof LangMainLayoutAuthenticatedUsers_tanstackRoute
  '/$lang/_mainLayout/_filter/products': typeof LangMainLayoutFilterProductsRoute
  '/$lang/_mainLayout/categories/$categoryId': typeof LangMainLayoutCategoriesCategoryIdRoute
  '/$lang/_mainLayout/news/$newsSlug': typeof LangMainLayoutNewsNewsSlugRoute
  '/$lang/_mainLayout/news/newsIndex': typeof LangMainLayoutNewsNewsIndexRoute
  '/$lang/_mainLayout/products/$productSlug': typeof LangMainLayoutProductsProductSlugRoute
  '/$lang/_mainLayout/_authenticated/checkout': typeof LangMainLayoutAuthenticatedCheckoutLazyRoute
  '/$lang/_mainLayout/_authenticated/profile': typeof LangMainLayoutAuthenticatedProfileLazyRoute
  '/$lang/_mainLayout/_authenticated/users': typeof LangMainLayoutAuthenticatedUsersLazyRoute
  '/$lang/_mainLayout/_authenticated/_CloudPayment/payment': typeof LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRoute
  '/$lang/_mainLayout/_authenticated/cart/$cartcode': typeof LangMainLayoutAuthenticatedCartCartcodeLazyRoute
  '/$lang/_mainLayout/_authenticated/cart/': typeof LangMainLayoutAuthenticatedCartIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/search'
    | '/test'
    | '/$lang/login'
    | '/$lang/passwordResetRequest'
    | '/$lang/register'
    | '/$lang/success'
    | '/$lang/failed'
    | '/$lang/'
    | '/$lang/password-reset/$token'
    | '/$lang/verify_email_reset/$token'
    | '/$lang/users_tanstack'
    | '/$lang/products'
    | '/$lang/categories/$categoryId'
    | '/$lang/news/$newsSlug'
    | '/$lang/news/newsIndex'
    | '/$lang/products/$productSlug'
    | '/$lang/checkout'
    | '/$lang/profile'
    | '/$lang/users'
    | '/$lang/payment'
    | '/$lang/cart/$cartcode'
    | '/$lang/cart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/search'
    | '/test'
    | '/$lang/login'
    | '/$lang/passwordResetRequest'
    | '/$lang/register'
    | '/$lang/success'
    | '/$lang/failed'
    | '/$lang/password-reset/$token'
    | '/$lang/verify_email_reset/$token'
    | '/$lang/users_tanstack'
    | '/$lang/products'
    | '/$lang/categories/$categoryId'
    | '/$lang/news/$newsSlug'
    | '/$lang/news/newsIndex'
    | '/$lang/products/$productSlug'
    | '/$lang/checkout'
    | '/$lang/profile'
    | '/$lang/users'
    | '/$lang/payment'
    | '/$lang/cart/$cartcode'
    | '/$lang/cart'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_mainLayout'
    | '/_search/search'
    | '/_test/test'
    | '/$lang/_auth/login'
    | '/$lang/_auth/passwordResetRequest'
    | '/$lang/_auth/register'
    | '/$lang/_mainLayout/_authenticated'
    | '/$lang/_paymentResult/success'
    | '/$lang/_paymentResult/failed'
    | '/$lang/_mainLayout/'
    | '/$lang/_auth/password-reset/$token'
    | '/$lang/_auth/verify_email_reset/$token'
    | '/$lang/_mainLayout/_authenticated/users_tanstack'
    | '/$lang/_mainLayout/_filter/products'
    | '/$lang/_mainLayout/categories/$categoryId'
    | '/$lang/_mainLayout/news/$newsSlug'
    | '/$lang/_mainLayout/news/newsIndex'
    | '/$lang/_mainLayout/products/$productSlug'
    | '/$lang/_mainLayout/_authenticated/checkout'
    | '/$lang/_mainLayout/_authenticated/profile'
    | '/$lang/_mainLayout/_authenticated/users'
    | '/$lang/_mainLayout/_authenticated/_CloudPayment/payment'
    | '/$lang/_mainLayout/_authenticated/cart/$cartcode'
    | '/$lang/_mainLayout/_authenticated/cart/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  SearchSearchRoute: typeof SearchSearchRoute
  TestTestLazyRoute: typeof TestTestLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_test/test': {
      id: '/_test/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestTestLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_search/search': {
      id: '/_search/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_mainLayout': {
      id: '/$lang/_mainLayout'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangMainLayoutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_mainLayout/': {
      id: '/$lang/_mainLayout/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangMainLayoutIndexRouteImport
      parentRoute: typeof LangMainLayoutRoute
    }
    '/$lang/_paymentResult/failed': {
      id: '/$lang/_paymentResult/failed'
      path: '/failed'
      fullPath: '/$lang/failed'
      preLoaderRoute: typeof LangPaymentResultFailedLazyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_paymentResult/success': {
      id: '/$lang/_paymentResult/success'
      path: '/success'
      fullPath: '/$lang/success'
      preLoaderRoute: typeof LangPaymentResultSuccessRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_mainLayout/_authenticated': {
      id: '/$lang/_mainLayout/_authenticated'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangMainLayoutAuthenticatedRouteImport
      parentRoute: typeof LangMainLayoutRoute
    }
    '/$lang/_auth/register': {
      id: '/$lang/_auth/register'
      path: '/register'
      fullPath: '/$lang/register'
      preLoaderRoute: typeof LangAuthRegisterRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_auth/passwordResetRequest': {
      id: '/$lang/_auth/passwordResetRequest'
      path: '/passwordResetRequest'
      fullPath: '/$lang/passwordResetRequest'
      preLoaderRoute: typeof LangAuthPasswordResetRequestRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_auth/login': {
      id: '/$lang/_auth/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangAuthLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_mainLayout/_authenticated/users': {
      id: '/$lang/_mainLayout/_authenticated/users'
      path: '/users'
      fullPath: '/$lang/users'
      preLoaderRoute: typeof LangMainLayoutAuthenticatedUsersLazyRouteImport
      parentRoute: typeof LangMainLayoutAuthenticatedRoute
    }
    '/$lang/_mainLayout/_authenticated/profile': {
      id: '/$lang/_mainLayout/_authenticated/profile'
      path: '/profile'
      fullPath: '/$lang/profile'
      preLoaderRoute: typeof LangMainLayoutAuthenticatedProfileLazyRouteImport
      parentRoute: typeof LangMainLayoutAuthenticatedRoute
    }
    '/$lang/_mainLayout/_authenticated/checkout': {
      id: '/$lang/_mainLayout/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/$lang/checkout'
      preLoaderRoute: typeof LangMainLayoutAuthenticatedCheckoutLazyRouteImport
      parentRoute: typeof LangMainLayoutAuthenticatedRoute
    }
    '/$lang/_mainLayout/products/$productSlug': {
      id: '/$lang/_mainLayout/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/$lang/products/$productSlug'
      preLoaderRoute: typeof LangMainLayoutProductsProductSlugRouteImport
      parentRoute: typeof LangMainLayoutRoute
    }
    '/$lang/_mainLayout/news/newsIndex': {
      id: '/$lang/_mainLayout/news/newsIndex'
      path: '/news/newsIndex'
      fullPath: '/$lang/news/newsIndex'
      preLoaderRoute: typeof LangMainLayoutNewsNewsIndexRouteImport
      parentRoute: typeof LangMainLayoutRoute
    }
    '/$lang/_mainLayout/news/$newsSlug': {
      id: '/$lang/_mainLayout/news/$newsSlug'
      path: '/news/$newsSlug'
      fullPath: '/$lang/news/$newsSlug'
      preLoaderRoute: typeof LangMainLayoutNewsNewsSlugRouteImport
      parentRoute: typeof LangMainLayoutRoute
    }
    '/$lang/_mainLayout/categories/$categoryId': {
      id: '/$lang/_mainLayout/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/$lang/categories/$categoryId'
      preLoaderRoute: typeof LangMainLayoutCategoriesCategoryIdRouteImport
      parentRoute: typeof LangMainLayoutRoute
    }
    '/$lang/_mainLayout/_filter/products': {
      id: '/$lang/_mainLayout/_filter/products'
      path: '/products'
      fullPath: '/$lang/products'
      preLoaderRoute: typeof LangMainLayoutFilterProductsRouteImport
      parentRoute: typeof LangMainLayoutRoute
    }
    '/$lang/_mainLayout/_authenticated/users_tanstack': {
      id: '/$lang/_mainLayout/_authenticated/users_tanstack'
      path: '/users_tanstack'
      fullPath: '/$lang/users_tanstack'
      preLoaderRoute: typeof LangMainLayoutAuthenticatedUsers_tanstackRouteImport
      parentRoute: typeof LangMainLayoutAuthenticatedRoute
    }
    '/$lang/_auth/verify_email_reset/$token': {
      id: '/$lang/_auth/verify_email_reset/$token'
      path: '/verify_email_reset/$token'
      fullPath: '/$lang/verify_email_reset/$token'
      preLoaderRoute: typeof LangAuthVerify_email_resetTokenRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_auth/password-reset/$token': {
      id: '/$lang/_auth/password-reset/$token'
      path: '/password-reset/$token'
      fullPath: '/$lang/password-reset/$token'
      preLoaderRoute: typeof LangAuthPasswordResetTokenRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_mainLayout/_authenticated/cart/': {
      id: '/$lang/_mainLayout/_authenticated/cart/'
      path: '/cart'
      fullPath: '/$lang/cart'
      preLoaderRoute: typeof LangMainLayoutAuthenticatedCartIndexLazyRouteImport
      parentRoute: typeof LangMainLayoutAuthenticatedRoute
    }
    '/$lang/_mainLayout/_authenticated/cart/$cartcode': {
      id: '/$lang/_mainLayout/_authenticated/cart/$cartcode'
      path: '/cart/$cartcode'
      fullPath: '/$lang/cart/$cartcode'
      preLoaderRoute: typeof LangMainLayoutAuthenticatedCartCartcodeLazyRouteImport
      parentRoute: typeof LangMainLayoutAuthenticatedRoute
    }
    '/$lang/_mainLayout/_authenticated/_CloudPayment/payment': {
      id: '/$lang/_mainLayout/_authenticated/_CloudPayment/payment'
      path: '/payment'
      fullPath: '/$lang/payment'
      preLoaderRoute: typeof LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRouteImport
      parentRoute: typeof LangMainLayoutAuthenticatedRoute
    }
  }
}

interface LangMainLayoutAuthenticatedRouteChildren {
  LangMainLayoutAuthenticatedUsers_tanstackRoute: typeof LangMainLayoutAuthenticatedUsers_tanstackRoute
  LangMainLayoutAuthenticatedCheckoutLazyRoute: typeof LangMainLayoutAuthenticatedCheckoutLazyRoute
  LangMainLayoutAuthenticatedProfileLazyRoute: typeof LangMainLayoutAuthenticatedProfileLazyRoute
  LangMainLayoutAuthenticatedUsersLazyRoute: typeof LangMainLayoutAuthenticatedUsersLazyRoute
  LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRoute: typeof LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRoute
  LangMainLayoutAuthenticatedCartCartcodeLazyRoute: typeof LangMainLayoutAuthenticatedCartCartcodeLazyRoute
  LangMainLayoutAuthenticatedCartIndexLazyRoute: typeof LangMainLayoutAuthenticatedCartIndexLazyRoute
}

const LangMainLayoutAuthenticatedRouteChildren: LangMainLayoutAuthenticatedRouteChildren =
  {
    LangMainLayoutAuthenticatedUsers_tanstackRoute:
      LangMainLayoutAuthenticatedUsers_tanstackRoute,
    LangMainLayoutAuthenticatedCheckoutLazyRoute:
      LangMainLayoutAuthenticatedCheckoutLazyRoute,
    LangMainLayoutAuthenticatedProfileLazyRoute:
      LangMainLayoutAuthenticatedProfileLazyRoute,
    LangMainLayoutAuthenticatedUsersLazyRoute:
      LangMainLayoutAuthenticatedUsersLazyRoute,
    LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRoute:
      LangMainLayoutAuthenticatedCloudPaymentPaymentLazyRoute,
    LangMainLayoutAuthenticatedCartCartcodeLazyRoute:
      LangMainLayoutAuthenticatedCartCartcodeLazyRoute,
    LangMainLayoutAuthenticatedCartIndexLazyRoute:
      LangMainLayoutAuthenticatedCartIndexLazyRoute,
  }

const LangMainLayoutAuthenticatedRouteWithChildren =
  LangMainLayoutAuthenticatedRoute._addFileChildren(
    LangMainLayoutAuthenticatedRouteChildren,
  )

interface LangMainLayoutRouteChildren {
  LangMainLayoutAuthenticatedRoute: typeof LangMainLayoutAuthenticatedRouteWithChildren
  LangMainLayoutIndexRoute: typeof LangMainLayoutIndexRoute
  LangMainLayoutFilterProductsRoute: typeof LangMainLayoutFilterProductsRoute
  LangMainLayoutCategoriesCategoryIdRoute: typeof LangMainLayoutCategoriesCategoryIdRoute
  LangMainLayoutNewsNewsSlugRoute: typeof LangMainLayoutNewsNewsSlugRoute
  LangMainLayoutNewsNewsIndexRoute: typeof LangMainLayoutNewsNewsIndexRoute
  LangMainLayoutProductsProductSlugRoute: typeof LangMainLayoutProductsProductSlugRoute
}

const LangMainLayoutRouteChildren: LangMainLayoutRouteChildren = {
  LangMainLayoutAuthenticatedRoute:
    LangMainLayoutAuthenticatedRouteWithChildren,
  LangMainLayoutIndexRoute: LangMainLayoutIndexRoute,
  LangMainLayoutFilterProductsRoute: LangMainLayoutFilterProductsRoute,
  LangMainLayoutCategoriesCategoryIdRoute:
    LangMainLayoutCategoriesCategoryIdRoute,
  LangMainLayoutNewsNewsSlugRoute: LangMainLayoutNewsNewsSlugRoute,
  LangMainLayoutNewsNewsIndexRoute: LangMainLayoutNewsNewsIndexRoute,
  LangMainLayoutProductsProductSlugRoute:
    LangMainLayoutProductsProductSlugRoute,
}

const LangMainLayoutRouteWithChildren = LangMainLayoutRoute._addFileChildren(
  LangMainLayoutRouteChildren,
)

interface LangRouteChildren {
  LangMainLayoutRoute: typeof LangMainLayoutRouteWithChildren
  LangAuthLoginRoute: typeof LangAuthLoginRoute
  LangAuthPasswordResetRequestRoute: typeof LangAuthPasswordResetRequestRoute
  LangAuthRegisterRoute: typeof LangAuthRegisterRoute
  LangPaymentResultSuccessRoute: typeof LangPaymentResultSuccessRoute
  LangPaymentResultFailedLazyRoute: typeof LangPaymentResultFailedLazyRoute
  LangAuthPasswordResetTokenRoute: typeof LangAuthPasswordResetTokenRoute
  LangAuthVerify_email_resetTokenRoute: typeof LangAuthVerify_email_resetTokenRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangMainLayoutRoute: LangMainLayoutRouteWithChildren,
  LangAuthLoginRoute: LangAuthLoginRoute,
  LangAuthPasswordResetRequestRoute: LangAuthPasswordResetRequestRoute,
  LangAuthRegisterRoute: LangAuthRegisterRoute,
  LangPaymentResultSuccessRoute: LangPaymentResultSuccessRoute,
  LangPaymentResultFailedLazyRoute: LangPaymentResultFailedLazyRoute,
  LangAuthPasswordResetTokenRoute: LangAuthPasswordResetTokenRoute,
  LangAuthVerify_email_resetTokenRoute: LangAuthVerify_email_resetTokenRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  SearchSearchRoute: SearchSearchRoute,
  TestTestLazyRoute: TestTestLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
