/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsProductSlugRouteImport } from './routes/products/$productSlug'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories/$categoryId'
import { Route as CartCartcodeRouteImport } from './routes/cart/$cartcode'

const IndexLazyRouteImport = createFileRoute('/')()
const CartIndexLazyRouteImport = createFileRoute('/cart/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CartIndexLazyRoute = CartIndexLazyRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cart/index.lazy').then((d) => d.Route))
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CartCartcodeRoute = CartCartcodeRouteImport.update({
  id: '/cart/$cartcode',
  path: '/cart/$cartcode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cart/$cartcode': typeof CartCartcodeRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/cart': typeof CartIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cart/$cartcode': typeof CartCartcodeRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/cart': typeof CartIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/cart/$cartcode': typeof CartCartcodeRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/cart/': typeof CartIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart/$cartcode'
    | '/categories/$categoryId'
    | '/products/$productSlug'
    | '/cart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart/$cartcode'
    | '/categories/$categoryId'
    | '/products/$productSlug'
    | '/cart'
  id:
    | '__root__'
    | '/'
    | '/cart/$cartcode'
    | '/categories/$categoryId'
    | '/products/$productSlug'
    | '/cart/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CartCartcodeRoute: typeof CartCartcodeRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
  CartIndexLazyRoute: typeof CartIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/$cartcode': {
      id: '/cart/$cartcode'
      path: '/cart/$cartcode'
      fullPath: '/cart/$cartcode'
      preLoaderRoute: typeof CartCartcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CartCartcodeRoute: CartCartcodeRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  CartIndexLazyRoute: CartIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
