# Generated by Django 5.2.9 on 2026-08-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('name_ru', models.CharField(max_length=64, null=True, unique=True)),
                ('name_en', models.CharField(max_length=64, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория Поста',
                'verbose_name_plural': 'Категории Постов',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок поста')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Заголовок поста')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(help_text='slug назначится автоматически', max_length=255, unique=True, verbose_name='URL')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст поста')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст поста')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст поста')),
                ('image', models.ImageField(upload_to='news_photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('D', 'Черновик'), ('P', 'Опубликовано'), ('A', 'в Архиве')], default='D', max_length=1, verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.category', verbose_name='Категория поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
