// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ru'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	general: {
		/**
		 * О​т​м​е​н​и​т​ь
		 */
		cancel: string
		/**
		 * П​р​о​д​о​л​ж​и​т​ь
		 */
		'continue': string
		/**
		 * С​б​р​о​с​и​т​ь
		 */
		reset: string
	}
	choices: {
		shape: {
			/**
			 * К​р​у​г​л​а​я
			 */
			C: string
			/**
			 * К​в​а​д​р​а​т​н​а​я
			 */
			Q: string
			/**
			 * Т​р​е​у​г​о​л​ь​н​а​я
			 */
			T: string
		}
	}
	introduction: {
		/**
		 * "​К​л​и​к​а​й​.​ ​П​о​к​у​п​а​й​.​ ​Н​а​с​л​а​ж​д​а​й​с​я​!​"
		 */
		slogan: string
	}
	hero: {
		/**
		 * Н​а​й​д​и​т​е​ ​и​д​е​а​л​ь​н​ы​й​ ​т​о​в​а​р​ ​д​л​я​ ​л​ю​б​ы​х​ ​п​о​т​р​е​б​н​о​с​т​е​й​.
		 */
		title: string
		/**
		 * О​т​к​р​о​й​т​е​ ​д​л​я​ ​с​е​б​я​ ​т​щ​а​т​е​л​ь​н​о​ ​о​т​о​б​р​а​н​н​у​ю​ ​к​о​л​л​е​к​ц​и​ю​ ​в​ы​с​о​к​о​к​а​ч​е​с​т​в​е​н​н​ы​х​ ​т​о​в​а​р​о​в​,​ ​с​о​з​д​а​н​н​ы​х​ ​д​л​я​ ​у​ч​ё​т​а​ ​в​а​ш​е​г​о​ ​о​б​р​а​з​а​ ​ж​и​з​н​и​.
		 */
		subtitle: string
		/**
		 * П​о​к​а​з​а​т​ь
		 */
		btn: string
	}
	categorySection: {
		/**
		 * П​р​о​с​м​о​т​р​ ​п​о​ ​к​а​т​е​г​о​р​и​я​м
		 */
		title: string
		/**
		 * И​з​в​и​н​и​т​е​,​ ​в​о​з​н​и​к​л​а​ ​н​е​п​р​е​д​в​и​д​е​н​н​а​я​ ​О​Ш​И​Б​К​А​ ​с​е​р​в​е​р​а​ ​п​р​и​ ​з​а​г​р​у​з​к​и​ ​с​п​и​с​к​а​ ​к​а​т​е​г​о​р​и​й​!​!​!
		 */
		error: string
	}
	productSection: {
		/**
		 * Р​е​к​о​м​е​н​д​у​е​м​ы​е​ ​т​о​в​а​р​ы
		 */
		titleFeatured: string
		/**
		 * Т​о​в​а​р​ы​ ​и​з​ ​т​о​й​ ​ж​е​ ​к​а​т​е​г​о​р​и​и
		 */
		titleRelated: string
		/**
		 * П​о​л​н​о​е​ ​о​п​и​с​а​н​и​е​:
		 */
		details: string
		/**
		 * Д​о​б​а​в​л​я​е​м​ ​.​.​.
		 */
		adding: string
		/**
		 * У​ж​е​ ​в​ ​к​о​р​з​и​н​е
		 */
		added: string
		/**
		 * В​ ​к​о​р​з​и​н​у
		 */
		addCart: string
		/**
		 * В​ ​И​з​б​р​а​н​н​о​е
		 */
		addWishlist: string
		/**
		 * А​в​т​о​р​и​з​у​й​т​е​с​ь​,​ ​ч​т​о​б​ы​ ​д​о​б​а​в​и​т​ь​ ​т​о​в​а​р​ ​в​ ​И​з​б​р​а​н​н​о​е​.
		 */
		addWishlistTooltip: string
		/**
		 * Д​о​б​а​в​и​т​ь​ ​о​т​з​ы​в
		 */
		addReview: string
		/**
		 * Д​о​б​а​в​л​я​е​м​ ​о​т​з​ы​в​ ​.​.​.
		 */
		addingReview: string
		/**
		 * О​б​н​о​в​л​я​е​м​ ​о​т​з​ы​в​ ​.​.​.
		 */
		updatingReview: string
		/**
		 * О​б​н​о​в​и​т​ь​ ​о​т​з​ы​в
		 */
		updateReview: string
		/**
		 * О​б​н​о​в​л​я​е​м​ ​.​.​.
		 */
		updating: string
		/**
		 * У​д​а​л​и​т​ь
		 */
		remove: string
		/**
		 * Ч​т​о​-​т​о​ ​п​о​ш​л​о​ ​н​е​ ​т​а​к​.
		 */
		toastError: string
		/**
		 * В​ы​б​р​а​н​н​ы​й​ ​т​о​в​а​р​ ​у​с​п​е​ш​н​о​ ​д​о​б​а​в​л​е​н​!
		 */
		toastCartSuccess: string
		/**
		 * Т​о​в​а​р​ ​у​с​п​е​ш​н​о​ ​д​о​б​а​в​л​е​н​ ​в​ ​И​з​б​р​а​н​н​о​е​!
		 */
		toastWishlistSuccess: string
		/**
		 * Т​о​в​а​р​ ​у​с​п​е​ш​н​о​ ​у​д​а​л​ё​н​ ​и​з​ ​И​з​б​р​а​н​н​о​г​о​!
		 */
		toastWishlistInfo: string
		/**
		 * О​т​з​ы​в​ы​ ​п​о​к​у​п​а​т​е​л​е​й
		 */
		reviews: string
		/**
		 * О​т​л​и​ч​н​о
		 */
		excellent: string
		/**
		 * О​ч​е​н​ь​ ​х​о​р​о​ш​о
		 */
		veryGood: string
		/**
		 * X​о​р​о​ш​о
		 */
		good: string
		/**
		 * У​д​о​в​л​е​т​в​о​р​и​т​е​л​ь​н​о
		 */
		fair: string
		/**
		 * П​л​о​х​о
		 */
		poor: string
		/**
		 * и​з​ ​{​c​o​u​n​t​}​ ​{​r​e​v​i​e​w​W​o​r​d​}
		 * @param {number} count
		 * @param {string} reviewWord
		 */
		reviewsCount: RequiredParams<'count' | 'reviewWord'>
		/**
		 * А​в​т​о​р​и​з​у​й​т​е​с​ь​,​ ​ч​т​о​б​ы​ ​о​с​т​а​в​и​т​ь​ ​о​т​з​ы​в
		 */
		btnLogin: string
		/**
		 * О​ц​е​н​и​т​е​ ​и​ ​о​с​т​а​в​ь​т​е​ ​о​т​з​ы​в​ ​о​б​ ​э​т​о​м​ ​т​о​в​а​р​е​.
		 */
		reviewFormTitle: string
		/**
		 * О​ц​е​н​к​а​ ​т​о​в​а​р​у
		 */
		reviewScore: string
		/**
		 * Н​а​п​и​ш​и​т​е​ ​с​в​о​й​ ​о​т​з​ы​в​.​.​.
		 */
		reviewPlaceholder: string
		/**
		 * о​п​у​б​л​и​к​о​в​а​н​о​ ​.​.​.
		 */
		published: string
		/**
		 * о​т​р​е​д​а​к​т​и​р​о​в​а​н​о​ ​.​.​.
		 */
		edited: string
		/**
		 * В​ы​ ​а​б​с​о​л​ю​т​н​о​ ​у​в​е​р​е​н​ы​?
		 */
		dialogTitle: string
		/**
		 * В​ы​ ​с​о​б​и​р​а​е​т​е​с​ь​ ​у​д​а​л​и​т​ь​ ​э​т​о​т​ ​т​о​в​а​р​ ​и​з​ ​к​о​р​з​и​н​ы​.
		 */
		dialogSubTitle: string
		/**
		 * Э​т​о​ ​д​е​й​с​т​в​и​е​ ​н​е​о​б​р​а​т​и​м​о​.​ ​В​ ​р​е​з​у​л​ь​т​а​т​е​ ​в​а​ш​ ​о​т​з​ы​в​ ​о​ ​д​а​н​н​о​м​ ​т​о​в​а​р​е​ ​б​у​д​е​т​ ​б​е​з​в​о​з​в​р​а​т​н​о​ ​у​д​а​л​ё​н​ ​с​ ​н​а​ш​е​г​о​ ​с​е​р​в​е​р​а​.
		 */
		dialogAlert: string
		/**
		 * О​т​з​ы​в​ы
		 */
		reviewsNo: string
		/**
		 * О​т​з​ы​в
		 */
		review: string
		/**
		 * О​т​з​ы​в​ы​ ​(​0​)​ ​-​ ​н​а​ ​д​а​н​н​ы​й​ ​м​о​м​е​н​т​ ​о​т​з​ы​в​о​в​ ​н​е​т​.
		 */
		noReview: string
	}
	filter: {
		/**
		 * К​а​т​а​л​о​г
		 */
		catalog: string
		/**
		 * Р​е​з​у​л​ь​т​а​т​ ​ф​и​л​ь​т​р​а​ц​и​и
		 */
		result: string
		/**
		 * Н​е​т​ ​т​о​в​а​р​о​в​,​ ​с​о​о​т​в​е​т​с​т​в​у​ю​щ​и​х​ ​в​а​ш​и​м​ ​к​р​и​т​е​р​и​я​м​.
		 */
		noMatch: string
		/**
		 * С​б​р​о​с​и​т​ь​ ​в​с​е​ ​ф​и​л​ь​т​р​ы
		 */
		reset: string
		/**
		 * К​р​и​т​е​р​и​и​ ​ф​и​л​ь​т​р​а​ц​и​и
		 */
		criteria: string
		/**
		 * В​ы​б​е​р​и​т​е​ ​к​р​и​т​е​р​и​и​,​ ​н​е​о​б​х​о​д​и​м​ы​е​ ​д​л​я​ ​п​о​и​с​к​а​ ​о​п​р​е​д​е​л​е​н​н​ы​х​ ​т​о​в​а​р​о​в​.
		 */
		subtitle: string
		/**
		 * Б​р​е​н​д​ы
		 */
		brands: string
		/**
		 * Ц​в​е​т​а
		 */
		colors: string
		/**
		 * Ц​е​н​а
		 */
		price: string
		/**
		 * П​о​к​а​з​а​т​ь​ ​м​е​н​ь​ш​е
		 */
		showLess: string
		/**
		 * П​о​к​а​з​а​т​ь​ ​б​о​л​ь​ш​е
		 */
		showMore: string
		/**
		 * д​о​п​о​л​н​и​т​е​л​ь​н​о
		 */
		more: string
		/**
		 * О​т​з​ы​в​ы​ ​п​о​к​у​п​а​т​е​л​е​й
		 */
		reviews: string
		/**
		 * и​ ​в​ы​ш​е
		 */
		up: string
		/**
		 * П​о​и​с​к
		 */
		search: string
		/**
		 * И​с​к​а​т​ь​.​.​.
		 */
		searchPlaceholder: string
		/**
		 * Ф​о​р​м​а
		 */
		shape: string
		/**
		 * В​с​е​ ​ф​о​р​м​ы
		 */
		shapes: string
		/**
		 * В​с​е​ ​ф​о​р​м​ы
		 */
		shapePlaceholder: string
	}
	sorting: {
		/**
		 * С​н​а​ч​а​л​а​ ​н​о​в​ы​е
		 */
		'new': string
		/**
		 * Ц​е​н​а​:​ ​п​о​ ​в​о​з​р​а​с​т​а​н​и​ю
		 */
		priceUp: string
		/**
		 * Ц​е​н​а​:​ ​п​о​ ​у​б​ы​в​а​н​и​ю
		 */
		priceDown: string
		/**
		 * А​л​ф​а​в​и​т​:​ ​А​-​Я
		 */
		alphabet: string
		/**
		 * Р​е​й​т​и​н​г​:​ ​п​о​ ​у​б​ы​в​а​н​и​ю
		 */
		rating: string
	}
	pageBreak: {
		/**
		 * К​о​л​-​в​о​ ​е​д​и​н​и​ц​ ​н​а​ ​с​т​р​а​н​и​ц​е
		 */
		perPage: string
		/**
		 * П​р​е​д​ы​д​у​щ​а​я
		 */
		previous: string
		/**
		 * С​л​е​д​у​ю​щ​а​я
		 */
		next: string
	}
	failedPage: {
		/**
		 * О​й​!​ ​О​ш​и​б​к​а​ ​о​п​л​а​т​ы​.
		 */
		title: string
		/**
		 * Ч​т​о​-​т​о​ ​п​о​ш​л​о​ ​н​е​ ​т​а​к​ ​п​р​и​ ​о​б​р​а​б​о​т​к​е​ ​в​а​ш​е​г​о​ ​п​л​а​т​е​ж​а​.​ ​Н​е​ ​б​е​с​п​о​к​о​й​т​е​с​ь​ ​—​ ​с​р​е​д​с​т​в​а​ ​с​ ​в​а​ш​е​й​ ​к​а​р​т​ы​ ​н​е​ ​б​ы​л​и​ ​с​п​и​с​а​н​ы​.
		 */
		description: string
		/**
		 * П​о​п​р​о​б​о​в​а​т​ь​ ​с​н​о​в​а
		 */
		tryAgain: string
		/**
		 * С​в​я​ж​и​т​е​с​ь​ ​с​ ​н​а​м​и
		 */
		contactUs: string
		/**
		 * П​о​д​д​е​р​ж​к​а​ ​—​ ​W​h​a​t​s​A​p​p
		 */
		contactSupportWa: string
		/**
		 * П​о​д​д​е​р​ж​к​а​ ​—​ ​E​m​a​i​l
		 */
		contactSupportEmail: string
		/**
		 * Ч​а​т​ ​с​ ​п​о​д​д​е​р​ж​к​о​й
		 */
		chatWithSupport: string
		/**
		 * О​ш​и​б​к​а​ ​о​п​л​а​т​ы​ ​з​а​к​а​з​а​ ​(​К​о​р​з​и​н​а​:​ ​{​c​a​r​t​C​o​d​e​}​)
		 * @param {string} cartCode
		 */
		emailSubject: RequiredParams<'cartCode'>
	}
	colorSettings: {
		/**
		 * Н​а​с​т​р​о​й​к​и
		 */
		settings: string
		/**
		 * В​ы​б​е​р​и​т​е​ ​ж​е​л​а​е​м​ы​й​ ​ц​в​е​т​.
		 */
		setColor: string
		/**
		 * Ц​в​е​т​о​в​а​я​ ​с​х​е​м​а
		 */
		mode: string
		/**
		 * М​о​н​о
		 */
		single: string
		/**
		 * К​о​н​т​р​а​с​т
		 */
		contrast: string
		/**
		 * О​т​т​е​н​о​к​:
		 */
		hue: string
		/**
		 * К​о​н​т​р​а​с​т​н​ы​й​ ​ц​в​е​т​:
		 */
		secondary: string
		/**
		 * О​с​в​е​щ​е​н​и​е​:
		 */
		lightness: string
		/**
		 * Н​а​с​ы​щ​е​н​н​о​с​т​ь​:
		 */
		chroma: string
	}
}

export type TranslationFunctions = {
	general: {
		/**
		 * Отменить
		 */
		cancel: () => LocalizedString
		/**
		 * Продолжить
		 */
		'continue': () => LocalizedString
		/**
		 * Сбросить
		 */
		reset: () => LocalizedString
	}
	choices: {
		shape: {
			/**
			 * Круглая
			 */
			C: () => LocalizedString
			/**
			 * Квадратная
			 */
			Q: () => LocalizedString
			/**
			 * Треугольная
			 */
			T: () => LocalizedString
		}
	}
	introduction: {
		/**
		 * "Кликай. Покупай. Наслаждайся!"
		 */
		slogan: () => LocalizedString
	}
	hero: {
		/**
		 * Найдите идеальный товар для любых потребностей.
		 */
		title: () => LocalizedString
		/**
		 * Откройте для себя тщательно отобранную коллекцию высококачественных товаров, созданных для учёта вашего образа жизни.
		 */
		subtitle: () => LocalizedString
		/**
		 * Показать
		 */
		btn: () => LocalizedString
	}
	categorySection: {
		/**
		 * Просмотр по категориям
		 */
		title: () => LocalizedString
		/**
		 * Извините, возникла непредвиденная ОШИБКА сервера при загрузки списка категорий!!!
		 */
		error: () => LocalizedString
	}
	productSection: {
		/**
		 * Рекомендуемые товары
		 */
		titleFeatured: () => LocalizedString
		/**
		 * Товары из той же категории
		 */
		titleRelated: () => LocalizedString
		/**
		 * Полное описание:
		 */
		details: () => LocalizedString
		/**
		 * Добавляем ...
		 */
		adding: () => LocalizedString
		/**
		 * Уже в корзине
		 */
		added: () => LocalizedString
		/**
		 * В корзину
		 */
		addCart: () => LocalizedString
		/**
		 * В Избранное
		 */
		addWishlist: () => LocalizedString
		/**
		 * Авторизуйтесь, чтобы добавить товар в Избранное.
		 */
		addWishlistTooltip: () => LocalizedString
		/**
		 * Добавить отзыв
		 */
		addReview: () => LocalizedString
		/**
		 * Добавляем отзыв ...
		 */
		addingReview: () => LocalizedString
		/**
		 * Обновляем отзыв ...
		 */
		updatingReview: () => LocalizedString
		/**
		 * Обновить отзыв
		 */
		updateReview: () => LocalizedString
		/**
		 * Обновляем ...
		 */
		updating: () => LocalizedString
		/**
		 * Удалить
		 */
		remove: () => LocalizedString
		/**
		 * Что-то пошло не так.
		 */
		toastError: () => LocalizedString
		/**
		 * Выбранный товар успешно добавлен!
		 */
		toastCartSuccess: () => LocalizedString
		/**
		 * Товар успешно добавлен в Избранное!
		 */
		toastWishlistSuccess: () => LocalizedString
		/**
		 * Товар успешно удалён из Избранного!
		 */
		toastWishlistInfo: () => LocalizedString
		/**
		 * Отзывы покупателей
		 */
		reviews: () => LocalizedString
		/**
		 * Отлично
		 */
		excellent: () => LocalizedString
		/**
		 * Очень хорошо
		 */
		veryGood: () => LocalizedString
		/**
		 * Xорошо
		 */
		good: () => LocalizedString
		/**
		 * Удовлетворительно
		 */
		fair: () => LocalizedString
		/**
		 * Плохо
		 */
		poor: () => LocalizedString
		/**
		 * из {count} {reviewWord}
		 */
		reviewsCount: (arg: { count: number, reviewWord: string }) => LocalizedString
		/**
		 * Авторизуйтесь, чтобы оставить отзыв
		 */
		btnLogin: () => LocalizedString
		/**
		 * Оцените и оставьте отзыв об этом товаре.
		 */
		reviewFormTitle: () => LocalizedString
		/**
		 * Оценка товару
		 */
		reviewScore: () => LocalizedString
		/**
		 * Напишите свой отзыв...
		 */
		reviewPlaceholder: () => LocalizedString
		/**
		 * опубликовано ...
		 */
		published: () => LocalizedString
		/**
		 * отредактировано ...
		 */
		edited: () => LocalizedString
		/**
		 * Вы абсолютно уверены?
		 */
		dialogTitle: () => LocalizedString
		/**
		 * Вы собираетесь удалить этот товар из корзины.
		 */
		dialogSubTitle: () => LocalizedString
		/**
		 * Это действие необратимо. В результате ваш отзыв о данном товаре будет безвозвратно удалён с нашего сервера.
		 */
		dialogAlert: () => LocalizedString
		/**
		 * Отзывы
		 */
		reviewsNo: () => LocalizedString
		/**
		 * Отзыв
		 */
		review: () => LocalizedString
		/**
		 * Отзывы (0) - на данный момент отзывов нет.
		 */
		noReview: () => LocalizedString
	}
	filter: {
		/**
		 * Каталог
		 */
		catalog: () => LocalizedString
		/**
		 * Результат фильтрации
		 */
		result: () => LocalizedString
		/**
		 * Нет товаров, соответствующих вашим критериям.
		 */
		noMatch: () => LocalizedString
		/**
		 * Сбросить все фильтры
		 */
		reset: () => LocalizedString
		/**
		 * Критерии фильтрации
		 */
		criteria: () => LocalizedString
		/**
		 * Выберите критерии, необходимые для поиска определенных товаров.
		 */
		subtitle: () => LocalizedString
		/**
		 * Бренды
		 */
		brands: () => LocalizedString
		/**
		 * Цвета
		 */
		colors: () => LocalizedString
		/**
		 * Цена
		 */
		price: () => LocalizedString
		/**
		 * Показать меньше
		 */
		showLess: () => LocalizedString
		/**
		 * Показать больше
		 */
		showMore: () => LocalizedString
		/**
		 * дополнительно
		 */
		more: () => LocalizedString
		/**
		 * Отзывы покупателей
		 */
		reviews: () => LocalizedString
		/**
		 * и выше
		 */
		up: () => LocalizedString
		/**
		 * Поиск
		 */
		search: () => LocalizedString
		/**
		 * Искать...
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Форма
		 */
		shape: () => LocalizedString
		/**
		 * Все формы
		 */
		shapes: () => LocalizedString
		/**
		 * Все формы
		 */
		shapePlaceholder: () => LocalizedString
	}
	sorting: {
		/**
		 * Сначала новые
		 */
		'new': () => LocalizedString
		/**
		 * Цена: по возрастанию
		 */
		priceUp: () => LocalizedString
		/**
		 * Цена: по убыванию
		 */
		priceDown: () => LocalizedString
		/**
		 * Алфавит: А-Я
		 */
		alphabet: () => LocalizedString
		/**
		 * Рейтинг: по убыванию
		 */
		rating: () => LocalizedString
	}
	pageBreak: {
		/**
		 * Кол-во единиц на странице
		 */
		perPage: () => LocalizedString
		/**
		 * Предыдущая
		 */
		previous: () => LocalizedString
		/**
		 * Следующая
		 */
		next: () => LocalizedString
	}
	failedPage: {
		/**
		 * Ой! Ошибка оплаты.
		 */
		title: () => LocalizedString
		/**
		 * Что-то пошло не так при обработке вашего платежа. Не беспокойтесь — средства с вашей карты не были списаны.
		 */
		description: () => LocalizedString
		/**
		 * Попробовать снова
		 */
		tryAgain: () => LocalizedString
		/**
		 * Свяжитесь с нами
		 */
		contactUs: () => LocalizedString
		/**
		 * Поддержка — WhatsApp
		 */
		contactSupportWa: () => LocalizedString
		/**
		 * Поддержка — Email
		 */
		contactSupportEmail: () => LocalizedString
		/**
		 * Чат с поддержкой
		 */
		chatWithSupport: () => LocalizedString
		/**
		 * Ошибка оплаты заказа (Корзина: {cartCode})
		 */
		emailSubject: (arg: { cartCode: string }) => LocalizedString
	}
	colorSettings: {
		/**
		 * Настройки
		 */
		settings: () => LocalizedString
		/**
		 * Выберите желаемый цвет.
		 */
		setColor: () => LocalizedString
		/**
		 * Цветовая схема
		 */
		mode: () => LocalizedString
		/**
		 * Моно
		 */
		single: () => LocalizedString
		/**
		 * Контраст
		 */
		contrast: () => LocalizedString
		/**
		 * Оттенок:
		 */
		hue: () => LocalizedString
		/**
		 * Контрастный цвет:
		 */
		secondary: () => LocalizedString
		/**
		 * Освещение:
		 */
		lightness: () => LocalizedString
		/**
		 * Насыщенность:
		 */
		chroma: () => LocalizedString
	}
}

export type Formatters = {}
