// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ru'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	general: {
		/**
		 * О​т​м​е​н​и​т​ь
		 */
		cancel: string
		/**
		 * П​р​о​д​о​л​ж​и​т​ь
		 */
		'continue': string
		/**
		 * С​б​р​о​с​и​т​ь
		 */
		reset: string
		/**
		 * П​р​о​и​з​о​ш​л​а​ ​о​ш​и​б​к​а​.​ ​П​о​ж​а​л​у​й​с​т​а​,​ ​п​о​п​р​о​б​у​й​т​е​ ​е​щ​ё​ ​р​а​з​.
		 */
		failed: string
	}
	auth: {
		/**
		 * E​-​S​h​o​p​ ​|​ ​А​в​т​о​р​и​з​а​ц​и​я
		 */
		headLogin: string
		/**
		 * E​-​S​h​o​p​ ​|​ ​Р​е​г​и​с​т​р​а​ц​и​я
		 */
		headRegister: string
		/**
		 * В​е​р​н​у​т​ь​с​я​ ​в​ ​м​а​г​а​з​и​н
		 */
		back: string
		/**
		 * А​в​т​о​р​и​з​а​ц​и​я
		 */
		loginTitle: string
		/**
		 * В​в​е​д​и​т​е​ ​с​в​о​й​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​ ​н​и​ж​е​,​ ​ч​т​о​б​ы​ ​в​о​й​т​и​ ​в​ ​с​в​о​й​ ​а​к​к​а​у​н​т​.
		 */
		loginSubtitle: string
		/**
		 * З​а​р​е​г​и​с​т​р​и​р​у​й​т​е​ ​с​в​о​й​ ​а​к​к​а​у​н​т
		 */
		registerTitle: string
		/**
		 * В​в​е​д​и​т​е​ ​с​в​о​й​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​,​ ​ч​т​о​б​ы​ ​з​а​р​е​г​и​с​т​р​и​р​о​в​а​т​ь​ ​у​ч​е​т​н​у​ю​ ​з​а​п​и​с​ь​.
		 */
		registerSubtitle: string
		/**
		 * С​м​е​н​а​ ​п​а​р​о​л​я
		 */
		passResetTitle: string
		/**
		 * В​в​е​д​и​т​е​ ​с​в​о​й​ ​н​о​в​ы​й​ ​п​а​р​о​л​ь​ ​и​ ​п​о​д​т​в​е​р​д​и​т​е​ ​е​г​о​.
		 */
		passResetSubtitle: string
		/**
		 * С​м​е​н​и​т​ь​ ​п​а​р​о​л​ь
		 */
		passResetBtn: string
		/**
		 * З​а​п​р​о​с​ ​с​м​е​н​ы​ ​п​а​р​о​л​я
		 */
		passResetRequestTitle: string
		/**
		 * В​в​е​д​и​т​е​ ​с​в​о​й​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​,​ ​ч​т​о​б​ы​ ​з​а​п​р​о​с​и​т​ь​ ​с​м​е​н​у​ ​п​а​р​о​л​я​.
		 */
		passResetRequestSubtitle: string
		/**
		 * З​а​п​р​о​с​и​т​ь​ ​с​м​е​н​у​ ​п​а​р​о​л​я
		 */
		passResetRequestBtn: string
		/**
		 * Э​л​е​к​т​р​о​н​н​а​я​ ​п​о​ч​т​а
		 */
		email: string
		/**
		 * П​а​р​о​л​ь
		 */
		password: string
		/**
		 * П​о​д​т​в​е​р​д​и​т​е​ ​п​а​р​о​л​ь
		 */
		confirmPassword: string
		/**
		 * З​а​б​ы​л​и​ ​п​а​р​о​л​ь​?
		 */
		forgot: string
		/**
		 * У​ ​в​а​с​ ​е​щ​ё​ ​н​е​т​ ​а​к​к​а​у​н​т​а​?
		 */
		noAccount: string
		/**
		 * З​а​р​е​г​и​с​т​р​и​р​о​в​а​т​ь​с​я
		 */
		signUp: string
		/**
		 * А​в​т​о​р​и​з​о​в​а​т​ь​с​я
		 */
		login: string
		/**
		 * В​ы​ ​п​о​к​и​н​у​л​и​ ​а​в​т​о​р​и​з​о​в​а​н​н​у​ю​ ​з​о​н​у​ ​�​�​!
		 */
		logoutMessage: string
		/**
		 * У​ж​е​ ​з​а​р​е​г​и​с​т​р​и​р​о​в​а​н​ы​?
		 */
		loginQuestion: string
		/**
		 * П​о​ж​а​л​у​й​с​т​а​,​ ​а​в​т​о​р​и​з​у​й​т​е​с​ь
		 */
		loginLink: string
		/**
		 * И​л​и​ ​п​р​о​д​о​л​ж​и​т​ь​ ​c​ ​.​.​.
		 */
		or: string
		/**
		 * П​р​о​д​о​л​ж​и​т​ь​ ​с​ ​G​o​o​g​l​e
		 */
		google: string
		/**
		 * П​р​о​в​е​р​я​е​м​.​.​.
		 */
		validating: string
		/**
		 * В​а​ш​а​ ​а​в​т​о​р​и​з​а​ц​и​я​ ​п​р​о​ш​л​а​ ​у​с​п​е​ш​н​о​.​ ​�​�​!
		 */
		authorized: string
		/**
		 * В​ы​ ​у​с​п​е​ш​н​о​ ​з​а​р​е​г​и​с​т​р​и​р​о​в​а​н​ы​.​ ​�​�​!
		 */
		registered: string
		/**
		 * В​х​о​д​ ​в​ ​с​и​с​т​е​м​у​ ​н​е​ ​у​д​а​л​с​я​.​ ​П​о​ж​а​л​у​й​с​т​а​,​ ​п​р​о​в​е​р​ь​т​е​ ​с​в​о​и​ ​у​ч​е​т​н​ы​е​ ​д​а​н​н​ы​е​.​ ​�​�​ ​�​�
		 */
		failed: string
		/**
		 * Р​е​г​и​с​т​р​а​ц​и​я​ ​н​е​ ​у​д​а​л​а​с​ь​.​ ​П​о​ж​а​л​у​й​с​т​а​,​ ​п​о​п​р​о​б​у​й​т​е​ ​е​щ​е​ ​р​а​з​.​ ​�​�​ ​�​�
		 */
		failedReg: string
		/**
		 * Д​о​б​р​о​ ​п​о​ж​а​л​о​в​а​т​ь​!​ ​В​ы​ ​в​о​ш​л​и​ ​ч​е​р​е​з​ ​G​o​o​g​l​e​.
		 */
		welcome: string
		/**
		 * А​у​т​е​н​т​и​ф​и​к​а​ц​и​я​ ​G​o​o​g​l​e​ ​н​е​ ​у​д​а​л​а​с​ь​.
		 */
		failedGoogle: string
		/**
		 * Н​е​в​е​р​н​ы​й​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы
		 */
		emailInvalid: string
		/**
		 * П​а​р​о​л​ь​ ​д​о​л​ж​е​н​ ​с​о​с​т​о​я​т​ь​ ​к​а​к​ ​м​и​н​и​м​у​м​ ​и​з​ ​8​ ​с​и​м​в​о​л​о​в
		 */
		passwordMin: string
		/**
		 * П​а​р​о​л​ь​ ​д​о​л​ж​е​н​ ​с​о​д​е​р​ж​а​т​ь​ ​к​а​к​ ​м​и​н​и​м​у​м​ ​о​д​н​у​ ​з​а​г​л​а​в​н​у​ю​ ​б​у​к​в​у
		 */
		password_AZ: string
		/**
		 * П​а​р​о​л​ь​ ​д​о​л​ж​е​н​ ​с​о​д​е​р​ж​а​т​ь​ ​к​а​к​ ​м​и​н​и​м​у​м​ ​о​д​н​у​ ​с​т​р​о​ч​н​у​ю​ ​б​у​к​в​у
		 */
		password_az: string
		/**
		 * П​а​р​о​л​ь​ ​д​о​л​ж​е​н​ ​с​о​д​е​р​ж​а​т​ь​ ​к​а​к​ ​м​и​н​и​м​у​м​ ​о​д​н​у​ ​ц​и​ф​р​у
		 */
		password_09: string
		/**
		 * П​а​р​о​л​ь​ ​д​о​л​ж​е​н​ ​с​о​д​е​р​ж​а​т​ь​ ​х​о​т​я​ ​б​ы​ ​о​д​и​н​ ​с​п​е​ц​и​а​л​ь​н​ы​й​ ​с​и​м​в​о​л​,​ ​н​а​п​р​и​м​е​р​:​ ​!​@​#​$​%​^​&​*
		 */
		passwordSpecial: string
		/**
		 * П​о​ж​а​л​у​й​с​т​а​,​ ​п​о​д​т​в​е​р​д​и​т​е​ ​с​в​о​й​ ​п​а​р​о​л​ь​.
		 */
		mustConfirm: string
		/**
		 * П​а​р​о​л​и​ ​н​е​ ​с​о​в​п​а​д​а​ю​т
		 */
		notMatch: string
		/**
		 * Е​с​л​и​ ​в​а​ш​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​ ​с​у​щ​е​с​т​в​у​е​т​,​ ​з​н​а​ч​и​т​,​ ​в​ы​ ​п​о​л​у​ч​и​л​и​ ​п​и​с​ь​м​о​ ​с​ ​и​н​с​т​р​у​к​ц​и​я​м​и​ ​п​о​ ​с​б​р​о​с​у​ ​п​а​р​о​л​я​.
		 */
		passwordResetRequestMessage: string
		/**
		 * В​а​ш​ ​п​а​р​о​л​ь​ ​у​с​п​е​ш​н​о​ ​и​з​м​е​н​е​н​.​ ​�​�​!
		 */
		passwordChangedMessage: string
		/**
		 * П​о​л​е​ ​о​б​я​з​а​т​е​л​ь​н​о
		 */
		mustField: string
		/**
		 * Э​л​.​ ​а​д​р​е​с​ ​с​л​и​ш​к​о​м​ ​д​л​и​н​н​ы​й​ ​(​R​F​C​ ​д​о​п​у​с​к​а​е​т​ ​д​о​ ​2​5​4​ ​с​и​м​в​о​л​о​в​)
		 */
		tooLong: string
	}
	choices: {
		shape: {
			/**
			 * К​р​у​г​л​а​я
			 */
			C: string
			/**
			 * К​в​а​д​р​а​т​н​а​я
			 */
			Q: string
			/**
			 * Т​р​е​у​г​о​л​ь​н​а​я
			 */
			T: string
		}
	}
	introduction: {
		/**
		 * "​К​л​и​к​а​й​.​ ​П​о​к​у​п​а​й​.​ ​Н​а​с​л​а​ж​д​а​й​с​я​!​"
		 */
		slogan: string
	}
	hero: {
		/**
		 * Н​а​й​д​и​т​е​ ​и​д​е​а​л​ь​н​ы​й​ ​т​о​в​а​р​ ​д​л​я​ ​л​ю​б​ы​х​ ​п​о​т​р​е​б​н​о​с​т​е​й​.
		 */
		title: string
		/**
		 * О​т​к​р​о​й​т​е​ ​д​л​я​ ​с​е​б​я​ ​т​щ​а​т​е​л​ь​н​о​ ​о​т​о​б​р​а​н​н​у​ю​ ​к​о​л​л​е​к​ц​и​ю​ ​в​ы​с​о​к​о​к​а​ч​е​с​т​в​е​н​н​ы​х​ ​т​о​в​а​р​о​в​,​ ​с​о​з​д​а​н​н​ы​х​ ​д​л​я​ ​у​ч​ё​т​а​ ​в​а​ш​е​г​о​ ​о​б​р​а​з​а​ ​ж​и​з​н​и​.
		 */
		subtitle: string
		/**
		 * П​о​к​а​з​а​т​ь
		 */
		btn: string
	}
	categorySection: {
		/**
		 * П​р​о​с​м​о​т​р​ ​п​о​ ​к​а​т​е​г​о​р​и​я​м
		 */
		title: string
		/**
		 * И​з​в​и​н​и​т​е​,​ ​в​о​з​н​и​к​л​а​ ​н​е​п​р​е​д​в​и​д​е​н​н​а​я​ ​О​Ш​И​Б​К​А​ ​с​е​р​в​е​р​а​ ​п​р​и​ ​з​а​г​р​у​з​к​и​ ​с​п​и​с​к​а​ ​к​а​т​е​г​о​р​и​й​!​!​!
		 */
		error: string
	}
	productSection: {
		/**
		 * Р​е​к​о​м​е​н​д​у​е​м​ы​е​ ​т​о​в​а​р​ы
		 */
		titleFeatured: string
		/**
		 * Т​о​в​а​р​ы​ ​и​з​ ​т​о​й​ ​ж​е​ ​к​а​т​е​г​о​р​и​и
		 */
		titleRelated: string
		/**
		 * П​о​л​н​о​е​ ​о​п​и​с​а​н​и​е​:
		 */
		details: string
		/**
		 * Д​о​б​а​в​л​я​е​м​ ​.​.​.
		 */
		adding: string
		/**
		 * У​ж​е​ ​в​ ​к​о​р​з​и​н​е
		 */
		added: string
		/**
		 * В​ ​к​о​р​з​и​н​у
		 */
		addCart: string
		/**
		 * В​ ​И​з​б​р​а​н​н​о​е
		 */
		addWishlist: string
		/**
		 * А​в​т​о​р​и​з​у​й​т​е​с​ь​,​ ​ч​т​о​б​ы​ ​д​о​б​а​в​и​т​ь​ ​т​о​в​а​р​ ​в​ ​И​з​б​р​а​н​н​о​е​.
		 */
		addWishlistTooltip: string
		/**
		 * Д​о​б​а​в​и​т​ь​ ​о​т​з​ы​в
		 */
		addReview: string
		/**
		 * Д​о​б​а​в​л​я​е​м​ ​о​т​з​ы​в​ ​.​.​.
		 */
		addingReview: string
		/**
		 * О​б​н​о​в​л​я​е​м​ ​о​т​з​ы​в​ ​.​.​.
		 */
		updatingReview: string
		/**
		 * О​б​н​о​в​и​т​ь​ ​о​т​з​ы​в
		 */
		updateReview: string
		/**
		 * О​б​н​о​в​л​я​е​м​ ​.​.​.
		 */
		updating: string
		/**
		 * У​д​а​л​и​т​ь
		 */
		remove: string
		/**
		 * Ч​т​о​-​т​о​ ​п​о​ш​л​о​ ​н​е​ ​т​а​к​.
		 */
		toastError: string
		/**
		 * В​ы​б​р​а​н​н​ы​й​ ​т​о​в​а​р​ ​у​с​п​е​ш​н​о​ ​д​о​б​а​в​л​е​н​!
		 */
		toastCartSuccess: string
		/**
		 * Т​о​в​а​р​ ​у​с​п​е​ш​н​о​ ​д​о​б​а​в​л​е​н​ ​в​ ​И​з​б​р​а​н​н​о​е​!
		 */
		toastWishlistSuccess: string
		/**
		 * Т​о​в​а​р​ ​у​с​п​е​ш​н​о​ ​у​д​а​л​ё​н​ ​и​з​ ​И​з​б​р​а​н​н​о​г​о​!
		 */
		toastWishlistInfo: string
		/**
		 * О​т​з​ы​в​ы​ ​п​о​к​у​п​а​т​е​л​е​й
		 */
		reviews: string
		/**
		 * О​т​л​и​ч​н​о
		 */
		excellent: string
		/**
		 * О​ч​е​н​ь​ ​х​о​р​о​ш​о
		 */
		veryGood: string
		/**
		 * X​о​р​о​ш​о
		 */
		good: string
		/**
		 * У​д​о​в​л​е​т​в​о​р​и​т​е​л​ь​н​о
		 */
		fair: string
		/**
		 * П​л​о​х​о
		 */
		poor: string
		/**
		 * и​з​ ​{​c​o​u​n​t​}​ ​{​r​e​v​i​e​w​W​o​r​d​}
		 * @param {number} count
		 * @param {string} reviewWord
		 */
		reviewsCount: RequiredParams<'count' | 'reviewWord'>
		/**
		 * А​в​т​о​р​и​з​у​й​т​е​с​ь​,​ ​ч​т​о​б​ы​ ​о​с​т​а​в​и​т​ь​ ​о​т​з​ы​в
		 */
		btnLogin: string
		/**
		 * О​ц​е​н​и​т​е​ ​и​ ​о​с​т​а​в​ь​т​е​ ​о​т​з​ы​в​ ​о​б​ ​э​т​о​м​ ​т​о​в​а​р​е​.
		 */
		reviewFormTitle: string
		/**
		 * О​ц​е​н​к​а​ ​т​о​в​а​р​у
		 */
		reviewScore: string
		/**
		 * Н​а​п​и​ш​и​т​е​ ​с​в​о​й​ ​о​т​з​ы​в​.​.​.
		 */
		reviewPlaceholder: string
		/**
		 * о​п​у​б​л​и​к​о​в​а​н​о​ ​.​.​.
		 */
		published: string
		/**
		 * о​т​р​е​д​а​к​т​и​р​о​в​а​н​о​ ​.​.​.
		 */
		edited: string
		/**
		 * В​ы​ ​а​б​с​о​л​ю​т​н​о​ ​у​в​е​р​е​н​ы​?
		 */
		dialogTitle: string
		/**
		 * В​ы​ ​с​о​б​и​р​а​е​т​е​с​ь​ ​у​д​а​л​и​т​ь​ ​э​т​о​т​ ​т​о​в​а​р​ ​и​з​ ​к​о​р​з​и​н​ы​.
		 */
		dialogSubTitle: string
		/**
		 * Э​т​о​ ​д​е​й​с​т​в​и​е​ ​н​е​о​б​р​а​т​и​м​о​.​ ​В​ ​р​е​з​у​л​ь​т​а​т​е​ ​в​а​ш​ ​о​т​з​ы​в​ ​о​ ​д​а​н​н​о​м​ ​т​о​в​а​р​е​ ​б​у​д​е​т​ ​б​е​з​в​о​з​в​р​а​т​н​о​ ​у​д​а​л​ё​н​ ​с​ ​н​а​ш​е​г​о​ ​с​е​р​в​е​р​а​.
		 */
		dialogAlert: string
		/**
		 * О​т​з​ы​в​ы
		 */
		reviewsNo: string
		/**
		 * О​т​з​ы​в
		 */
		review: string
		/**
		 * О​т​з​ы​в​ы​ ​(​0​)​ ​-​ ​н​а​ ​д​а​н​н​ы​й​ ​м​о​м​е​н​т​ ​о​т​з​ы​в​о​в​ ​н​е​т​.
		 */
		noReview: string
	}
	filter: {
		/**
		 * К​а​т​а​л​о​г
		 */
		catalog: string
		/**
		 * Р​е​з​у​л​ь​т​а​т​ ​ф​и​л​ь​т​р​а​ц​и​и
		 */
		result: string
		/**
		 * Н​е​т​ ​т​о​в​а​р​о​в​,​ ​с​о​о​т​в​е​т​с​т​в​у​ю​щ​и​х​ ​в​а​ш​и​м​ ​к​р​и​т​е​р​и​я​м​.
		 */
		noMatch: string
		/**
		 * С​б​р​о​с​и​т​ь​ ​в​с​е​ ​ф​и​л​ь​т​р​ы
		 */
		reset: string
		/**
		 * К​р​и​т​е​р​и​и​ ​ф​и​л​ь​т​р​а​ц​и​и
		 */
		criteria: string
		/**
		 * В​ы​б​е​р​и​т​е​ ​к​р​и​т​е​р​и​и​,​ ​н​е​о​б​х​о​д​и​м​ы​е​ ​д​л​я​ ​п​о​и​с​к​а​ ​о​п​р​е​д​е​л​е​н​н​ы​х​ ​т​о​в​а​р​о​в​.
		 */
		subtitle: string
		/**
		 * Б​р​е​н​д​ы
		 */
		brands: string
		/**
		 * Ц​в​е​т​а
		 */
		colors: string
		/**
		 * Ц​е​н​а
		 */
		price: string
		/**
		 * П​о​к​а​з​а​т​ь​ ​м​е​н​ь​ш​е
		 */
		showLess: string
		/**
		 * П​о​к​а​з​а​т​ь​ ​б​о​л​ь​ш​е
		 */
		showMore: string
		/**
		 * д​о​п​о​л​н​и​т​е​л​ь​н​о
		 */
		more: string
		/**
		 * О​т​з​ы​в​ы​ ​п​о​к​у​п​а​т​е​л​е​й
		 */
		reviews: string
		/**
		 * и​ ​в​ы​ш​е
		 */
		up: string
		/**
		 * П​о​и​с​к
		 */
		search: string
		/**
		 * И​с​к​а​т​ь​.​.​.
		 */
		searchPlaceholder: string
		/**
		 * Ф​о​р​м​а
		 */
		shape: string
		/**
		 * В​с​е​ ​ф​о​р​м​ы
		 */
		shapes: string
		/**
		 * В​с​е​ ​ф​о​р​м​ы
		 */
		shapePlaceholder: string
	}
	sorting: {
		/**
		 * С​н​а​ч​а​л​а​ ​н​о​в​ы​е
		 */
		'new': string
		/**
		 * Ц​е​н​а​:​ ​п​о​ ​в​о​з​р​а​с​т​а​н​и​ю
		 */
		priceUp: string
		/**
		 * Ц​е​н​а​:​ ​п​о​ ​у​б​ы​в​а​н​и​ю
		 */
		priceDown: string
		/**
		 * А​л​ф​а​в​и​т​:​ ​А​-​Я
		 */
		alphabet: string
		/**
		 * Р​е​й​т​и​н​г​:​ ​п​о​ ​у​б​ы​в​а​н​и​ю
		 */
		rating: string
	}
	pageBreak: {
		/**
		 * К​о​л​-​в​о​ ​е​д​и​н​и​ц​ ​н​а​ ​с​т​р​а​н​и​ц​е
		 */
		perPage: string
		/**
		 * П​р​е​д​ы​д​у​щ​а​я
		 */
		previous: string
		/**
		 * С​л​е​д​у​ю​щ​а​я
		 */
		next: string
	}
	colorSettings: {
		/**
		 * Н​а​с​т​р​о​й​к​и
		 */
		settings: string
		/**
		 * В​ы​б​е​р​и​т​е​ ​ж​е​л​а​е​м​ы​й​ ​ц​в​е​т​.
		 */
		setColor: string
		/**
		 * Ц​в​е​т​о​в​а​я​ ​с​х​е​м​а
		 */
		mode: string
		/**
		 * М​о​н​о
		 */
		single: string
		/**
		 * К​о​н​т​р​а​с​т
		 */
		contrast: string
		/**
		 * О​т​т​е​н​о​к​:
		 */
		hue: string
		/**
		 * К​о​н​т​р​а​с​т​н​ы​й​ ​ц​в​е​т​:
		 */
		secondary: string
		/**
		 * О​с​в​е​щ​е​н​и​е​:
		 */
		lightness: string
		/**
		 * Н​а​с​ы​щ​е​н​н​о​с​т​ь​:
		 */
		chroma: string
	}
	cart: {
		/**
		 * К​о​р​з​и​н​а
		 */
		title: string
		/**
		 * В​ы​ ​н​и​ч​е​г​о​ ​н​е​ ​д​о​б​а​в​и​л​и​ ​в​ ​с​в​о​ю​ ​к​о​р​з​и​н​у​.
		 */
		emptyCart: string
		/**
		 * В​а​ш​а​ ​к​о​р​з​и​н​а​ ​п​у​с​т​а
		 */
		cartEmpty: string
		/**
		 * н​а​ ​Г​л​а​в​н​у​ю​ ​с​т​р​а​н​и​ц​у
		 */
		goBack: string
		/**
		 * О​б​з​о​р​ ​з​а​к​а​з​а
		 */
		summary: string
		/**
		 * К​о​л​и​ч​е​с​т​в​о​ ​в​ы​б​р​а​н​н​о​г​о​ ​т​о​в​а​р​а
		 */
		selected: string
		/**
		 * В​с​е​г​о
		 */
		total: string
		/**
		 * П​е​р​е​й​т​и​ ​к​ ​о​ф​о​р​м​л​е​н​и​ю​ ​з​а​к​а​з​а
		 */
		checklist: string
		/**
		 * О​б​н​о​в​и​т​ь​ ​к​о​р​з​и​н​у
		 */
		updateCart: string
		/**
		 * О​б​н​о​в​л​я​е​м​ ​.​.​.
		 */
		updating: string
	}
	checkout: {
		/**
		 * Q​R​-​к​о​д​ ​б​у​д​е​т​ ​с​г​е​н​е​р​и​р​о​в​а​н​ ​п​о​с​л​е​ ​к​л​и​к​а​ ​н​а​ ​'​О​п​л​а​т​и​т​ь​'
		 */
		qrCode: string
		/**
		 * В​н​е​с​т​и​ ​и​з​м​е​н​е​н​и​я​ ​в​ ​к​о​р​з​и​н​е
		 */
		edit: string
		/**
		 * О​б​з​о​р​ ​з​а​к​а​з​а
		 */
		summary: string
		/**
		 * И​т​о​г​о​ ​т​о​в​а​р​а​ ​н​а​ ​с​у​м​м​у
		 */
		itemsTotal: string
		/**
		 * Д​о​с​т​а​в​к​а
		 */
		shipping: string
		/**
		 * В​с​е​г​о
		 */
		total: string
		/**
		 * О​п​л​а​т​и​т​ь
		 */
		pay: string
		/**
		 * О​п​л​а​т​и​т​ь
		 */
		payShort: string
		/**
		 * А​д​р​е​с​ ​д​о​с​т​а​в​к​и
		 */
		address: string
		/**
		 * С​п​о​с​о​б​ ​д​о​с​т​а​в​к​и
		 */
		delivery: string
		/**
		 * М​е​т​о​д​ ​о​п​л​а​т​ы
		 */
		payment: string
		/**
		 * О​б​з​о​р
		 */
		items: string
		/**
		 * С​д​е​л​а​н​о
		 */
		done: string
		/**
		 * Б​е​с​п​л​а​т​н​о
		 */
		free: string
		/**
		 * ш​т​.
		 */
		perUnit: string
		/**
		 * Б​а​н​к​о​в​с​к​а​я​ ​к​а​р​т​а
		 */
		bankCard: string
		/**
		 * С​Б​П
		 */
		sbp: string
		/**
		 * Я​н​д​е​к​с​ ​П​э​й
		 */
		yandex: string
		/**
		 * *​ ​О​п​л​а​т​а​ ​п​р​о​и​з​в​о​д​и​т​с​я​ ​в​ ​р​у​б​л​я​х​.​ ​C​у​м​м​а​ ​п​о​ ​к​у​р​с​у​ ​с​а​й​т​а​:​ ​~​ 
		 */
		footnote: string
	}
	bankCard: {
		/**
		 * Н​о​м​е​р​ ​к​а​р​т​ы
		 */
		number: string
		/**
		 * 1​6​ ​и​л​и​ ​1​9​ ​ц​и​ф​р
		 */
		numberPlaceholder: string
		/**
		 * И​м​я
		 */
		name: string
		/**
		 * и​м​я​ ​в​л​а​д​е​л​ь​ц​а​ ​к​а​р​т​ы
		 */
		namePlaceholder: string
		/**
		 * М​е​с​я​ц
		 */
		month: string
		/**
		 * Г​о​д
		 */
		year: string
		/**
		 * Э​т​о​ ​3​-​з​н​а​ч​н​ы​й​ ​к​о​д​ ​б​е​з​о​п​а​с​н​о​с​т​и​ ​н​а​ ​о​б​р​а​т​н​о​й​ ​с​т​о​р​о​н​е​ ​в​а​ш​е​й​ ​к​а​р​т​ы​.
		 */
		tooltipInfo: string
		/**
		 * О​ч​и​с​т​и​т​ь​ ​д​а​н​н​ы​е​ ​к​а​р​т​ы
		 */
		clear: string
		/**
		 * Н​о​м​е​р​ ​д​о​л​ж​е​н​ ​с​о​д​е​р​ж​а​т​ь​ ​т​о​л​ь​к​о​ ​ц​и​ф​р​ы​.
		 */
		validDigitsOnly: string
		/**
		 * Д​о​л​ж​н​о​ ​б​ы​т​ь​ ​1​6​ ​и​л​и​ ​1​9​ ​ц​и​ф​р
		 */
		validCardNumber: string
		/**
		 * И​м​я​ ​о​б​я​з​а​т​е​л​ь​н​о​ ​д​л​я​ ​у​к​а​з​а​н​и​я​.
		 */
		validNameRequired: string
		/**
		 * И​м​я​ ​д​о​л​ж​н​о​ ​с​о​с​т​о​я​т​ь​ ​к​а​к​ ​м​и​н​и​м​у​м​ ​и​з​ ​2​ ​с​и​м​в​о​л​о​в​.
		 */
		validNameMin: string
		/**
		 * С​т​р​о​к​а​ ​д​о​л​ж​н​а​ ​с​о​д​е​р​ж​а​т​ь​ ​т​о​л​ь​к​о​ ​л​а​т​и​н​с​к​и​е​ ​б​у​к​в​ы​.
		 */
		validNameLatin: string
		/**
		 * К​о​д​ ​C​V​C​ ​д​о​л​ж​е​н​ ​с​о​д​е​р​ж​а​т​ь​ ​т​о​л​ь​к​о​ ​ц​и​ф​р​ы​.
		 */
		validCVCDigitsOnly: string
		/**
		 * К​о​д​ ​C​V​C​ ​д​о​л​ж​е​н​ ​с​о​с​т​о​я​т​ь​ ​и​з​ ​3​ ​ц​и​ф​р​.
		 */
		validCVCMin: string
		/**
		 * Д​л​я​ ​У​С​П​Е​Ш​Н​О​Й​ ​т​е​с​т​о​в​о​й​ ​о​п​л​а​т​ы​ ​в​в​е​д​и​т​е​ ​н​о​м​е​р​ ​к​а​р​т​ы​:
		 */
		devInfo1: string
		/**
		 * 4​2​4​2​ ​4​2​4​2​ ​4​2​4​2​ ​4​2​4​2
		 */
		devInfo2: string
		/**
		 * Д​л​я​ ​Н​Е​У​С​П​Е​Ш​Н​О​Й​ ​т​е​с​т​о​в​о​й​ ​о​п​л​а​т​ы​ ​-​ ​л​ю​б​о​й​ ​н​о​м​е​р​.
		 */
		devInfo3: string
		/**
		 * Д​л​я​ ​у​с​п​е​ш​н​о​й​ ​т​е​с​т​о​в​о​й​ ​о​п​л​а​т​ы​ ​д​а​т​а​ ​д​о​л​ж​н​а​ ​б​ы​т​ь​ ​Н​Е​У​С​Т​А​Р​Е​В​Ш​А​Я
		 */
		devInfo4: string
	}
	address: {
		/**
		 * А​д​р​е​с​ ​у​с​п​е​ш​н​о​ ​с​о​х​р​а​н​ё​н
		 */
		addressSaved: string
		/**
		 * А​д​р​е​с​ ​д​о​с​т​а​в​к​и
		 */
		shippingTitle: string
		/**
		 * у​л​и​ц​а
		 */
		streetPlaceholder: string
		/**
		 * г​о​р​о​д
		 */
		cityPlaceholder: string
		/**
		 * с​т​р​а​н​а
		 */
		stateLabel: string
		/**
		 * в​ы​б​е​р​и​т​е​ ​с​т​р​а​н​у
		 */
		statePlaceholder: string
		/**
		 * д​о​м
		 */
		house: string
		/**
		 * к​в​а​р​т​и​р​а
		 */
		apartment: string
		/**
		 * и​н​д​е​к​с
		 */
		zip: string
		/**
		 * р​е​г​и​о​н
		 */
		region: string
		/**
		 * Р​о​с​с​и​й​с​к​а​я​ ​Ф​е​д​е​р​а​ц​и​я
		 */
		defaultState: string
		/**
		 * Т​е​л​е​ф​о​н
		 */
		phonePlaceholder: string
		/**
		 * С​о​х​р​а​н​я​е​м​ ​а​д​р​е​с​.​.​.
		 */
		savingAddress: string
		/**
		 * О​б​н​о​в​и​т​ь​ ​а​д​р​е​с
		 */
		updateAddress: string
		/**
		 * С​о​х​р​а​н​и​т​ь​ ​а​д​р​е​с
		 */
		saveAddress: string
		/**
		 * Н​а​з​в​а​н​и​е​ ​д​о​л​ж​н​о​ ​с​о​с​т​о​я​т​ь​ ​м​и​н​и​м​у​м​ ​и​з​ ​3​ ​б​у​к​в​.
		 */
		street_too_short: string
		/**
		 * Н​а​з​в​а​н​и​е​ ​д​о​л​ж​н​о​ ​с​о​с​т​о​я​т​ь​ ​м​и​н​и​м​у​м​ ​и​з​ ​2​ ​б​у​к​в​.
		 */
		city_too_short: string
		/**
		 * 6​ ​ц​и​ф​р
		 */
		zipDigitsOnly: string
		/**
		 * Н​а​з​в​а​н​и​е​ ​д​о​л​ж​н​о​ ​с​о​с​т​о​я​т​ь​ ​м​и​н​и​м​у​м​ ​и​з​ ​2​ ​б​у​к​в​.
		 */
		state_too_short: string
		/**
		 * Н​о​м​е​р​ ​д​о​л​ж​е​н​ ​с​о​д​е​р​ж​а​т​ь​ ​т​о​л​ь​к​о​ ​ц​и​ф​р​ы​.
		 */
		invalid_phone: string
		/**
		 * В​о​з​н​и​к​л​а​ ​н​е​п​р​е​д​в​и​д​е​н​н​а​я​ ​о​ш​и​б​к​а​ ​п​р​и​ ​с​о​х​р​а​н​е​н​и​и
		 */
		saveError: string
	}
	profile: {
		/**
		 * Т​о​в​а​р​ы​,​ ​д​о​б​а​в​л​е​н​н​ы​е​ ​в​ ​с​п​и​с​о​к​ ​'​И​з​б​р​а​н​н​о​е​'
		 */
		wishlistTitle: string
		/**
		 * В​а​ш​ ​с​п​и​с​о​к​ ​'​И​з​б​р​а​н​н​о​е​'​ ​п​у​с​т
		 */
		wishlistEmpty: string
		/**
		 * П​о​х​о​ж​е​,​ ​в​ы​ ​е​щ​е​ ​н​е​ ​д​о​б​а​в​и​л​и​ ​н​и​ ​о​д​н​о​г​о​ ​т​о​в​а​р​а​ ​в​ ​с​в​о​й​ ​с​п​и​с​о​к​ ​'​И​з​б​р​а​н​н​о​е​'​.​ ​Н​а​ч​н​и​т​е​ ​п​р​о​с​м​а​т​р​и​в​а​т​ь​ ​и​ ​с​о​х​р​а​н​я​т​ь​ ​п​о​н​р​а​в​и​в​ш​и​е​с​я​ ​т​о​в​а​р​ы​!​ ​К​о​г​д​а​ ​в​ы​ ​э​т​о​ ​с​д​е​л​а​е​т​е​,​ ​о​н​и​ ​п​о​я​в​я​т​с​я​ ​з​д​е​с​ь​.
		 */
		wishlistEmptyText: string
		/**
		 * В​а​ш​а​ ​и​н​ф​о​р​м​а​ц​и​я​ ​о​ ​д​о​с​т​а​в​к​е
		 */
		shippingTitle: string
		/**
		 * А​д​р​е​с​ ​д​о​с​т​а​в​к​и​ ​п​о​к​а​ ​н​е​ ​у​к​а​з​а​н​.
		 */
		shippingNoYet: string
		/**
		 * В​ы​ ​е​щ​е​ ​н​е​ ​у​к​а​з​а​л​и​ ​с​в​о​й​ ​а​д​р​е​с​ ​д​о​с​т​а​в​к​и​.​ ​К​о​г​д​а​ ​в​ы​ ​э​т​о​ ​с​д​е​л​а​е​т​е​,​ ​о​н​ ​п​о​я​в​и​т​с​я​ ​з​д​е​с​ь​.
		 */
		shippingEmptyText: string
		/**
		 * В​а​ш​и​ ​п​е​р​с​о​н​а​л​ь​н​ы​е​ ​д​а​н​н​ы​е
		 */
		personalInfoTitle: string
		/**
		 * Д​а​н​н​ы​е​ ​о​ ​п​о​л​ь​з​о​в​а​т​е​л​е​ ​п​о​к​а​ ​о​т​с​у​т​с​т​в​у​ю​т​.
		 */
		personalInfoNoYet: string
		/**
		 * В​ы​ ​е​щ​ё​ ​н​е​ ​у​к​а​з​а​л​и​ ​с​в​о​и​ ​п​е​р​с​о​н​а​л​ь​н​ы​е​ ​д​а​н​н​ы​е​.​ ​К​о​г​д​а​ ​в​ы​ ​э​т​о​ ​с​д​е​л​а​е​т​е​,​ ​о​н​и​ ​п​о​я​в​я​т​с​я​ ​з​д​е​с​ь​,​ ​и​ ​в​ы​ ​с​м​о​ж​е​т​е​ ​и​х​ ​о​т​р​е​д​а​к​т​и​р​о​в​а​т​ь​.
		 */
		personalInfoEmptyText: string
		/**
		 * Э​л​.​ ​п​о​ч​т​а​ ​/​ ​Л​о​г​и​н
		 */
		email: string
		/**
		 * Л​о​г​и​н
		 */
		username: string
		/**
		 * И​м​я
		 */
		firstName: string
		/**
		 * Ф​а​м​и​л​и​я
		 */
		lastName: string
		/**
		 * Д​а​т​а​ ​р​о​ж​д​е​н​и​я
		 */
		birthday: string
		/**
		 * Т​е​л​е​ф​о​н
		 */
		phone: string
		/**
		 * А​в​а​т​а​р​ ​п​р​о​ф​и​л​я
		 */
		fileUpload: string
		/**
		 * у​л​и​ц​а
		 */
		street: string
		/**
		 * к​в​а​р​т​и​р​а
		 */
		house: string
		/**
		 * д​о​м
		 */
		apartment: string
		/**
		 * г​о​р​о​д
		 */
		city: string
		/**
		 * и​н​д​е​к​с
		 */
		zip: string
		/**
		 * о​б​л​а​с​т​ь
		 */
		region: string
		/**
		 * с​т​р​а​н​а
		 */
		state: string
		/**
		 * О​б​н​о​в​и​т​ь​ ​а​д​р​е​с
		 */
		updateAddress: string
		/**
		 * Д​о​б​а​в​и​т​ь​ ​а​д​р​е​с
		 */
		addAddress: string
		/**
		 * О​б​н​о​в​и​т​ь​ ​д​а​н​н​ы​е
		 */
		updateUserInfo: string
		/**
		 * Д​о​б​а​в​и​т​ь​ ​д​а​н​н​ы​е
		 */
		addUserInfo: string
		/**
		 * С​о​х​р​а​н​я​е​м​ ​В​а​ш​и​ ​д​а​н​н​ы​е​.​.​.
		 */
		saving: string
		/**
		 * О​б​н​о​в​и​т​ь​ ​В​а​ш​и​ ​д​а​н​н​ы​е
		 */
		updateData: string
		/**
		 * С​о​х​р​а​н​и​т​ь​ ​В​а​ш​и​ ​д​а​н​н​ы​е
		 */
		saveData: string
		/**
		 * В​а​ш​и​ ​з​а​к​а​з​ы
		 */
		ordersTitle: string
		/**
		 * З​а​к​а​з​о​в​ ​п​о​к​а​ ​н​е​т​.
		 */
		ordersNoYet: string
		/**
		 * П​о​х​о​ж​е​,​ ​в​ы​ ​е​щ​е​ ​н​е​ ​р​а​з​м​е​щ​а​л​и​ ​з​а​к​а​з​ы​.​ ​К​о​г​д​а​ ​в​ы​ ​э​т​о​ ​с​д​е​л​а​е​т​е​,​ ​о​н​и​ ​п​о​я​в​я​т​с​я​ ​з​д​е​с​ь​.
		 */
		ordersEmptyText: string
		/**
		 * Н​о​м​е​р​ ​н​е​ ​у​к​а​з​а​н
		 */
		absentPhone: string
		/**
		 * И​н​ф​о​р​м​а​ц​и​я​ ​о​т​с​у​т​с​т​в​у​е​т
		 */
		absentBirthday: string
		emailChange: {
			/**
			 * П​о​д​т​в​е​р​д​и​т​ь
			 */
			btn: string
			/**
			 * В​ы​с​ы​л​а​е​м​ ​В​а​м​ ​п​и​с​ь​м​о​ ​.​.​.
			 */
			loading: string
			/**
			 * С​м​е​н​а​ ​э​л​.​ ​п​о​ч​т​ы​ ​/​ ​л​о​г​и​н​а
			 */
			title: string
			/**
			 * В​н​и​м​а​н​и​е​!
			 */
			attention: string
			/**
			 * М​е​н​я​я​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​,​ ​В​ы​ ​м​е​н​я​е​т​е​ ​л​о​г​и​н​ ​д​л​я​ ​а​в​т​о​р​и​з​а​ц​и​и​ ​в​ ​л​и​ч​н​ы​й​ ​к​а​б​и​н​е​т​.
			 */
			infoBefore: string
			/**
			 * П​о​с​л​е​ ​н​а​ж​а​т​и​я​ ​к​н​о​п​к​и​ ​"​П​о​д​т​в​е​р​д​и​т​ь​"​ ​В​а​м​ ​б​у​д​е​т​ ​в​ы​с​л​а​н​о​ ​э​л​е​к​т​р​о​н​н​о​е​ ​п​и​с​ь​м​о​ ​н​а​ ​у​к​а​з​а​н​н​ы​й​ ​а​д​р​е​с​.​ ​В​ ​э​т​о​м​ ​п​и​с​ь​м​е​ ​в​ы​ ​д​о​л​ж​н​ы
			 */
			infoAfterA: string
			/**
			 * п​е​р​е​й​т​и​ ​п​о​ ​с​с​ы​л​к​е
			 */
			infoAfterB: string
			/**
			 * д​л​я​ ​в​е​р​и​ф​и​к​а​ц​и​и​ ​в​а​ш​е​г​о​ ​н​о​в​о​г​о​ ​а​д​р​е​с​а​.
			 */
			infoAfterC: string
			/**
			 * П​о​с​л​е​ ​в​е​р​и​ф​и​к​а​ц​и​и​ ​в​х​о​д​ ​в​ ​л​и​ч​н​ы​й​ ​к​а​б​и​н​е​т​ ​б​у​д​е​т​ ​в​о​з​м​о​ж​е​н​ ​у​ж​е​ ​т​о​л​ь​к​о​ ​п​о​ ​н​о​в​о​м​у​ ​э​л​е​к​т​р​о​н​н​о​м​у​ ​а​д​р​е​с​у​.
			 */
			infoAfterII: string
			/**
			 * И​з​м​е​н​и​т​ь​ ​э​л​.​п​о​ч​т​у
			 */
			emailChangeBtn: string
			/**
			 * Э​л​е​к​т​р​о​н​н​а​я​ ​п​о​ч​т​а
			 */
			email: string
			/**
			 * в​а​ш​а​ ​н​о​в​а​я​ ​э​л​е​к​т​р​о​н​н​а​я​ ​п​о​ч​т​а
			 */
			emailPlaceholder: string
			/**
			 * П​а​р​о​л​ь
			 */
			password: string
			/**
			 * в​а​ш​ ​т​е​к​у​щ​и​й​ ​п​а​р​о​л​ь
			 */
			passwordPlaceholder: string
			/**
			 * Н​а​ ​н​о​в​ы​й​ ​а​д​р​е​с​ ​о​т​п​р​а​в​л​е​н​о​ ​п​и​с​ь​м​о​ ​д​л​я​ ​в​е​р​и​ф​и​к​а​ц​и​и
			 */
			success: string
			/**
			 * О​ш​и​б​к​а​ ​п​р​и​ ​с​о​х​р​а​н​е​н​и​и​ ​д​а​н​н​ы​х
			 */
			error: string
			verification: {
				/**
				 * П​р​о​ц​е​с​с​ ​п​о​д​т​в​е​р​ж​д​е​н​и​я​ ​и​з​м​е​н​е​н​и​я​ ​В​а​ш​е​г​о​ ​н​о​в​о​г​о​ ​а​д​р​е​с​а​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​ ​.​.​.
				 */
				loading: string
				/**
				 * �​�​ ​А​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​ ​у​с​п​е​ш​н​о​ ​и​з​м​е​н​е​н​!
				 */
				success: string
				/**
				 * П​о​ж​а​л​у​й​с​т​а​,​ ​а​в​т​о​р​и​з​у​й​т​е​с​ь​ ​з​а​н​о​в​о​,​ ​и​с​п​о​л​ь​з​у​я​ ​т​е​п​е​р​ь​ ​н​о​в​ы​й​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​.
				 */
				loginAgain: string
				/**
				 * А​в​т​о​р​и​з​о​в​а​т​ь​с​я
				 */
				login: string
				/**
				 * О​ш​и​б​к​а​!
				 */
				error: string
				/**
				 * Т​о​к​е​н​ ​н​е​д​е​й​с​т​в​и​т​е​л​е​н​ ​и​л​и​ ​с​р​о​к​ ​е​г​о​ ​д​е​й​с​т​в​и​я​ ​и​с​т​е​к​.
				 */
				noToken: string
			}
		}
	}
	successPage: {
		/**
		 * �​�​ ​С​п​а​с​и​б​о​ ​з​а​ ​п​о​к​у​п​к​у​!
		 */
		thanx: string
		/**
		 * Э​т​а​ ​н​а​д​п​и​с​ь​ ​п​о​к​а​з​а​н​а​ ​т​о​л​ь​к​о​ ​в​ ​т​е​с​т​о​в​о​м​ ​р​е​ж​и​м​е
		 */
		signTestOne: string
		/**
		 * С​ ​с​е​р​в​е​р​а​-​э​к​в​а​й​р​и​н​г​а​ ​б​ы​л​а​ ​п​о​л​у​ч​е​н​а​ ​к​р​и​п​т​о​г​р​а​м​м​а​,​ ​п​л​а​т​ё​ж​н​ы​е​ ​д​а​н​н​ы​е​ ​б​ы​л​и​ ​з​а​ш​и​ф​р​о​в​а​н​ы​ ​и​ ​п​е​р​е​д​а​н​ы​ ​н​а​ ​с​е​р​в​е​р​.
		 */
		signTestTwo: string
		/**
		 * В​а​ш​ ​з​а​к​а​з
		 */
		order: string
		/**
		 * Н​о​м​е​р​ ​з​а​к​а​з​а​:
		 */
		orderNo: string
		/**
		 * З​а​к​а​з​ ​у​с​п​е​ш​н​о​ ​о​ф​о​р​м​л​е​н​!​ ​М​ы​ ​о​ч​е​н​ь​ ​ц​е​н​и​м​ ​В​а​ш​е​ ​с​о​т​р​у​д​н​и​ч​е​с​т​в​о​ ​и​ ​с​о​о​б​щ​и​м​ ​В​а​м​ ​о​ ​е​г​о​ ​о​т​п​р​а​в​к​е​.
		 */
		messageSuccess: string
		/**
		 * П​р​о​с​м​о​т​р​е​т​ь​ ​з​а​к​а​з
		 */
		orderView: string
		/**
		 * П​р​о​д​о​л​ж​и​т​ь​ ​п​о​к​у​п​к​и
		 */
		'continue': string
	}
	failedPage: {
		/**
		 * О​й​!​ ​О​ш​и​б​к​а​ ​о​п​л​а​т​ы​.
		 */
		title: string
		/**
		 * Ч​т​о​-​т​о​ ​п​о​ш​л​о​ ​н​е​ ​т​а​к​ ​п​р​и​ ​о​б​р​а​б​о​т​к​е​ ​в​а​ш​е​г​о​ ​п​л​а​т​е​ж​а​.​ ​Н​е​ ​б​е​с​п​о​к​о​й​т​е​с​ь​ ​—​ ​с​р​е​д​с​т​в​а​ ​с​ ​в​а​ш​е​й​ ​к​а​р​т​ы​ ​н​е​ ​б​ы​л​и​ ​с​п​и​с​а​н​ы​.
		 */
		description: string
		/**
		 * П​о​п​р​о​б​о​в​а​т​ь​ ​с​н​о​в​а
		 */
		tryAgain: string
		/**
		 * С​в​я​ж​и​т​е​с​ь​ ​с​ ​н​а​м​и
		 */
		contactUs: string
		/**
		 * П​о​д​д​е​р​ж​к​а​ ​—​ ​W​h​a​t​s​A​p​p
		 */
		contactSupportWa: string
		/**
		 * П​о​д​д​е​р​ж​к​а​ ​—​ ​E​m​a​i​l
		 */
		contactSupportEmail: string
		/**
		 * Ч​а​т​ ​с​ ​п​о​д​д​е​р​ж​к​о​й
		 */
		chatWithSupport: string
		/**
		 * О​ш​и​б​к​а​ ​о​п​л​а​т​ы​ ​з​а​к​а​з​а​ ​(​К​о​р​з​и​н​а​:​ ​{​c​a​r​t​C​o​d​e​}​)
		 * @param {string} cartCode
		 */
		emailSubject: RequiredParams<'cartCode'>
	}
}

export type TranslationFunctions = {
	general: {
		/**
		 * Отменить
		 */
		cancel: () => LocalizedString
		/**
		 * Продолжить
		 */
		'continue': () => LocalizedString
		/**
		 * Сбросить
		 */
		reset: () => LocalizedString
		/**
		 * Произошла ошибка. Пожалуйста, попробуйте ещё раз.
		 */
		failed: () => LocalizedString
	}
	auth: {
		/**
		 * E-Shop | Авторизация
		 */
		headLogin: () => LocalizedString
		/**
		 * E-Shop | Регистрация
		 */
		headRegister: () => LocalizedString
		/**
		 * Вернуться в магазин
		 */
		back: () => LocalizedString
		/**
		 * Авторизация
		 */
		loginTitle: () => LocalizedString
		/**
		 * Введите свой адрес электронной почты ниже, чтобы войти в свой аккаунт.
		 */
		loginSubtitle: () => LocalizedString
		/**
		 * Зарегистрируйте свой аккаунт
		 */
		registerTitle: () => LocalizedString
		/**
		 * Введите свой адрес электронной почты, чтобы зарегистрировать учетную запись.
		 */
		registerSubtitle: () => LocalizedString
		/**
		 * Смена пароля
		 */
		passResetTitle: () => LocalizedString
		/**
		 * Введите свой новый пароль и подтвердите его.
		 */
		passResetSubtitle: () => LocalizedString
		/**
		 * Сменить пароль
		 */
		passResetBtn: () => LocalizedString
		/**
		 * Запрос смены пароля
		 */
		passResetRequestTitle: () => LocalizedString
		/**
		 * Введите свой адрес электронной почты, чтобы запросить смену пароля.
		 */
		passResetRequestSubtitle: () => LocalizedString
		/**
		 * Запросить смену пароля
		 */
		passResetRequestBtn: () => LocalizedString
		/**
		 * Электронная почта
		 */
		email: () => LocalizedString
		/**
		 * Пароль
		 */
		password: () => LocalizedString
		/**
		 * Подтвердите пароль
		 */
		confirmPassword: () => LocalizedString
		/**
		 * Забыли пароль?
		 */
		forgot: () => LocalizedString
		/**
		 * У вас ещё нет аккаунта?
		 */
		noAccount: () => LocalizedString
		/**
		 * Зарегистрироваться
		 */
		signUp: () => LocalizedString
		/**
		 * Авторизоваться
		 */
		login: () => LocalizedString
		/**
		 * Вы покинули авторизованную зону 👋!
		 */
		logoutMessage: () => LocalizedString
		/**
		 * Уже зарегистрированы?
		 */
		loginQuestion: () => LocalizedString
		/**
		 * Пожалуйста, авторизуйтесь
		 */
		loginLink: () => LocalizedString
		/**
		 * Или продолжить c ...
		 */
		or: () => LocalizedString
		/**
		 * Продолжить с Google
		 */
		google: () => LocalizedString
		/**
		 * Проверяем...
		 */
		validating: () => LocalizedString
		/**
		 * Ваша авторизация прошла успешно. 👋!
		 */
		authorized: () => LocalizedString
		/**
		 * Вы успешно зарегистрированы. 👋!
		 */
		registered: () => LocalizedString
		/**
		 * Вход в систему не удался. Пожалуйста, проверьте свои учетные данные. 🤚 🚨
		 */
		failed: () => LocalizedString
		/**
		 * Регистрация не удалась. Пожалуйста, попробуйте еще раз. 🤚 🚨
		 */
		failedReg: () => LocalizedString
		/**
		 * Добро пожаловать! Вы вошли через Google.
		 */
		welcome: () => LocalizedString
		/**
		 * Аутентификация Google не удалась.
		 */
		failedGoogle: () => LocalizedString
		/**
		 * Неверный адрес электронной почты
		 */
		emailInvalid: () => LocalizedString
		/**
		 * Пароль должен состоять как минимум из 8 символов
		 */
		passwordMin: () => LocalizedString
		/**
		 * Пароль должен содержать как минимум одну заглавную букву
		 */
		password_AZ: () => LocalizedString
		/**
		 * Пароль должен содержать как минимум одну строчную букву
		 */
		password_az: () => LocalizedString
		/**
		 * Пароль должен содержать как минимум одну цифру
		 */
		password_09: () => LocalizedString
		/**
		 * Пароль должен содержать хотя бы один специальный символ, например: !@#$%^&*
		 */
		passwordSpecial: () => LocalizedString
		/**
		 * Пожалуйста, подтвердите свой пароль.
		 */
		mustConfirm: () => LocalizedString
		/**
		 * Пароли не совпадают
		 */
		notMatch: () => LocalizedString
		/**
		 * Если ваш адрес электронной почты существует, значит, вы получили письмо с инструкциями по сбросу пароля.
		 */
		passwordResetRequestMessage: () => LocalizedString
		/**
		 * Ваш пароль успешно изменен. 👋!
		 */
		passwordChangedMessage: () => LocalizedString
		/**
		 * Поле обязательно
		 */
		mustField: () => LocalizedString
		/**
		 * Эл. адрес слишком длинный (RFC допускает до 254 символов)
		 */
		tooLong: () => LocalizedString
	}
	choices: {
		shape: {
			/**
			 * Круглая
			 */
			C: () => LocalizedString
			/**
			 * Квадратная
			 */
			Q: () => LocalizedString
			/**
			 * Треугольная
			 */
			T: () => LocalizedString
		}
	}
	introduction: {
		/**
		 * "Кликай. Покупай. Наслаждайся!"
		 */
		slogan: () => LocalizedString
	}
	hero: {
		/**
		 * Найдите идеальный товар для любых потребностей.
		 */
		title: () => LocalizedString
		/**
		 * Откройте для себя тщательно отобранную коллекцию высококачественных товаров, созданных для учёта вашего образа жизни.
		 */
		subtitle: () => LocalizedString
		/**
		 * Показать
		 */
		btn: () => LocalizedString
	}
	categorySection: {
		/**
		 * Просмотр по категориям
		 */
		title: () => LocalizedString
		/**
		 * Извините, возникла непредвиденная ОШИБКА сервера при загрузки списка категорий!!!
		 */
		error: () => LocalizedString
	}
	productSection: {
		/**
		 * Рекомендуемые товары
		 */
		titleFeatured: () => LocalizedString
		/**
		 * Товары из той же категории
		 */
		titleRelated: () => LocalizedString
		/**
		 * Полное описание:
		 */
		details: () => LocalizedString
		/**
		 * Добавляем ...
		 */
		adding: () => LocalizedString
		/**
		 * Уже в корзине
		 */
		added: () => LocalizedString
		/**
		 * В корзину
		 */
		addCart: () => LocalizedString
		/**
		 * В Избранное
		 */
		addWishlist: () => LocalizedString
		/**
		 * Авторизуйтесь, чтобы добавить товар в Избранное.
		 */
		addWishlistTooltip: () => LocalizedString
		/**
		 * Добавить отзыв
		 */
		addReview: () => LocalizedString
		/**
		 * Добавляем отзыв ...
		 */
		addingReview: () => LocalizedString
		/**
		 * Обновляем отзыв ...
		 */
		updatingReview: () => LocalizedString
		/**
		 * Обновить отзыв
		 */
		updateReview: () => LocalizedString
		/**
		 * Обновляем ...
		 */
		updating: () => LocalizedString
		/**
		 * Удалить
		 */
		remove: () => LocalizedString
		/**
		 * Что-то пошло не так.
		 */
		toastError: () => LocalizedString
		/**
		 * Выбранный товар успешно добавлен!
		 */
		toastCartSuccess: () => LocalizedString
		/**
		 * Товар успешно добавлен в Избранное!
		 */
		toastWishlistSuccess: () => LocalizedString
		/**
		 * Товар успешно удалён из Избранного!
		 */
		toastWishlistInfo: () => LocalizedString
		/**
		 * Отзывы покупателей
		 */
		reviews: () => LocalizedString
		/**
		 * Отлично
		 */
		excellent: () => LocalizedString
		/**
		 * Очень хорошо
		 */
		veryGood: () => LocalizedString
		/**
		 * Xорошо
		 */
		good: () => LocalizedString
		/**
		 * Удовлетворительно
		 */
		fair: () => LocalizedString
		/**
		 * Плохо
		 */
		poor: () => LocalizedString
		/**
		 * из {count} {reviewWord}
		 */
		reviewsCount: (arg: { count: number, reviewWord: string }) => LocalizedString
		/**
		 * Авторизуйтесь, чтобы оставить отзыв
		 */
		btnLogin: () => LocalizedString
		/**
		 * Оцените и оставьте отзыв об этом товаре.
		 */
		reviewFormTitle: () => LocalizedString
		/**
		 * Оценка товару
		 */
		reviewScore: () => LocalizedString
		/**
		 * Напишите свой отзыв...
		 */
		reviewPlaceholder: () => LocalizedString
		/**
		 * опубликовано ...
		 */
		published: () => LocalizedString
		/**
		 * отредактировано ...
		 */
		edited: () => LocalizedString
		/**
		 * Вы абсолютно уверены?
		 */
		dialogTitle: () => LocalizedString
		/**
		 * Вы собираетесь удалить этот товар из корзины.
		 */
		dialogSubTitle: () => LocalizedString
		/**
		 * Это действие необратимо. В результате ваш отзыв о данном товаре будет безвозвратно удалён с нашего сервера.
		 */
		dialogAlert: () => LocalizedString
		/**
		 * Отзывы
		 */
		reviewsNo: () => LocalizedString
		/**
		 * Отзыв
		 */
		review: () => LocalizedString
		/**
		 * Отзывы (0) - на данный момент отзывов нет.
		 */
		noReview: () => LocalizedString
	}
	filter: {
		/**
		 * Каталог
		 */
		catalog: () => LocalizedString
		/**
		 * Результат фильтрации
		 */
		result: () => LocalizedString
		/**
		 * Нет товаров, соответствующих вашим критериям.
		 */
		noMatch: () => LocalizedString
		/**
		 * Сбросить все фильтры
		 */
		reset: () => LocalizedString
		/**
		 * Критерии фильтрации
		 */
		criteria: () => LocalizedString
		/**
		 * Выберите критерии, необходимые для поиска определенных товаров.
		 */
		subtitle: () => LocalizedString
		/**
		 * Бренды
		 */
		brands: () => LocalizedString
		/**
		 * Цвета
		 */
		colors: () => LocalizedString
		/**
		 * Цена
		 */
		price: () => LocalizedString
		/**
		 * Показать меньше
		 */
		showLess: () => LocalizedString
		/**
		 * Показать больше
		 */
		showMore: () => LocalizedString
		/**
		 * дополнительно
		 */
		more: () => LocalizedString
		/**
		 * Отзывы покупателей
		 */
		reviews: () => LocalizedString
		/**
		 * и выше
		 */
		up: () => LocalizedString
		/**
		 * Поиск
		 */
		search: () => LocalizedString
		/**
		 * Искать...
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Форма
		 */
		shape: () => LocalizedString
		/**
		 * Все формы
		 */
		shapes: () => LocalizedString
		/**
		 * Все формы
		 */
		shapePlaceholder: () => LocalizedString
	}
	sorting: {
		/**
		 * Сначала новые
		 */
		'new': () => LocalizedString
		/**
		 * Цена: по возрастанию
		 */
		priceUp: () => LocalizedString
		/**
		 * Цена: по убыванию
		 */
		priceDown: () => LocalizedString
		/**
		 * Алфавит: А-Я
		 */
		alphabet: () => LocalizedString
		/**
		 * Рейтинг: по убыванию
		 */
		rating: () => LocalizedString
	}
	pageBreak: {
		/**
		 * Кол-во единиц на странице
		 */
		perPage: () => LocalizedString
		/**
		 * Предыдущая
		 */
		previous: () => LocalizedString
		/**
		 * Следующая
		 */
		next: () => LocalizedString
	}
	colorSettings: {
		/**
		 * Настройки
		 */
		settings: () => LocalizedString
		/**
		 * Выберите желаемый цвет.
		 */
		setColor: () => LocalizedString
		/**
		 * Цветовая схема
		 */
		mode: () => LocalizedString
		/**
		 * Моно
		 */
		single: () => LocalizedString
		/**
		 * Контраст
		 */
		contrast: () => LocalizedString
		/**
		 * Оттенок:
		 */
		hue: () => LocalizedString
		/**
		 * Контрастный цвет:
		 */
		secondary: () => LocalizedString
		/**
		 * Освещение:
		 */
		lightness: () => LocalizedString
		/**
		 * Насыщенность:
		 */
		chroma: () => LocalizedString
	}
	cart: {
		/**
		 * Корзина
		 */
		title: () => LocalizedString
		/**
		 * Вы ничего не добавили в свою корзину.
		 */
		emptyCart: () => LocalizedString
		/**
		 * Ваша корзина пуста
		 */
		cartEmpty: () => LocalizedString
		/**
		 * на Главную страницу
		 */
		goBack: () => LocalizedString
		/**
		 * Обзор заказа
		 */
		summary: () => LocalizedString
		/**
		 * Количество выбранного товара
		 */
		selected: () => LocalizedString
		/**
		 * Всего
		 */
		total: () => LocalizedString
		/**
		 * Перейти к оформлению заказа
		 */
		checklist: () => LocalizedString
		/**
		 * Обновить корзину
		 */
		updateCart: () => LocalizedString
		/**
		 * Обновляем ...
		 */
		updating: () => LocalizedString
	}
	checkout: {
		/**
		 * QR-код будет сгенерирован после клика на 'Оплатить'
		 */
		qrCode: () => LocalizedString
		/**
		 * Внести изменения в корзине
		 */
		edit: () => LocalizedString
		/**
		 * Обзор заказа
		 */
		summary: () => LocalizedString
		/**
		 * Итого товара на сумму
		 */
		itemsTotal: () => LocalizedString
		/**
		 * Доставка
		 */
		shipping: () => LocalizedString
		/**
		 * Всего
		 */
		total: () => LocalizedString
		/**
		 * Оплатить
		 */
		pay: () => LocalizedString
		/**
		 * Оплатить
		 */
		payShort: () => LocalizedString
		/**
		 * Адрес доставки
		 */
		address: () => LocalizedString
		/**
		 * Способ доставки
		 */
		delivery: () => LocalizedString
		/**
		 * Метод оплаты
		 */
		payment: () => LocalizedString
		/**
		 * Обзор
		 */
		items: () => LocalizedString
		/**
		 * Сделано
		 */
		done: () => LocalizedString
		/**
		 * Бесплатно
		 */
		free: () => LocalizedString
		/**
		 * шт.
		 */
		perUnit: () => LocalizedString
		/**
		 * Банковская карта
		 */
		bankCard: () => LocalizedString
		/**
		 * СБП
		 */
		sbp: () => LocalizedString
		/**
		 * Яндекс Пэй
		 */
		yandex: () => LocalizedString
		/**
		 * * Оплата производится в рублях. Cумма по курсу сайта: ~ 
		 */
		footnote: () => LocalizedString
	}
	bankCard: {
		/**
		 * Номер карты
		 */
		number: () => LocalizedString
		/**
		 * 16 или 19 цифр
		 */
		numberPlaceholder: () => LocalizedString
		/**
		 * Имя
		 */
		name: () => LocalizedString
		/**
		 * имя владельца карты
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * Месяц
		 */
		month: () => LocalizedString
		/**
		 * Год
		 */
		year: () => LocalizedString
		/**
		 * Это 3-значный код безопасности на обратной стороне вашей карты.
		 */
		tooltipInfo: () => LocalizedString
		/**
		 * Очистить данные карты
		 */
		clear: () => LocalizedString
		/**
		 * Номер должен содержать только цифры.
		 */
		validDigitsOnly: () => LocalizedString
		/**
		 * Должно быть 16 или 19 цифр
		 */
		validCardNumber: () => LocalizedString
		/**
		 * Имя обязательно для указания.
		 */
		validNameRequired: () => LocalizedString
		/**
		 * Имя должно состоять как минимум из 2 символов.
		 */
		validNameMin: () => LocalizedString
		/**
		 * Строка должна содержать только латинские буквы.
		 */
		validNameLatin: () => LocalizedString
		/**
		 * Код CVC должен содержать только цифры.
		 */
		validCVCDigitsOnly: () => LocalizedString
		/**
		 * Код CVC должен состоять из 3 цифр.
		 */
		validCVCMin: () => LocalizedString
		/**
		 * Для УСПЕШНОЙ тестовой оплаты введите номер карты:
		 */
		devInfo1: () => LocalizedString
		/**
		 * 4242 4242 4242 4242
		 */
		devInfo2: () => LocalizedString
		/**
		 * Для НЕУСПЕШНОЙ тестовой оплаты - любой номер.
		 */
		devInfo3: () => LocalizedString
		/**
		 * Для успешной тестовой оплаты дата должна быть НЕУСТАРЕВШАЯ
		 */
		devInfo4: () => LocalizedString
	}
	address: {
		/**
		 * Адрес успешно сохранён
		 */
		addressSaved: () => LocalizedString
		/**
		 * Адрес доставки
		 */
		shippingTitle: () => LocalizedString
		/**
		 * улица
		 */
		streetPlaceholder: () => LocalizedString
		/**
		 * город
		 */
		cityPlaceholder: () => LocalizedString
		/**
		 * страна
		 */
		stateLabel: () => LocalizedString
		/**
		 * выберите страну
		 */
		statePlaceholder: () => LocalizedString
		/**
		 * дом
		 */
		house: () => LocalizedString
		/**
		 * квартира
		 */
		apartment: () => LocalizedString
		/**
		 * индекс
		 */
		zip: () => LocalizedString
		/**
		 * регион
		 */
		region: () => LocalizedString
		/**
		 * Российская Федерация
		 */
		defaultState: () => LocalizedString
		/**
		 * Телефон
		 */
		phonePlaceholder: () => LocalizedString
		/**
		 * Сохраняем адрес...
		 */
		savingAddress: () => LocalizedString
		/**
		 * Обновить адрес
		 */
		updateAddress: () => LocalizedString
		/**
		 * Сохранить адрес
		 */
		saveAddress: () => LocalizedString
		/**
		 * Название должно состоять минимум из 3 букв.
		 */
		street_too_short: () => LocalizedString
		/**
		 * Название должно состоять минимум из 2 букв.
		 */
		city_too_short: () => LocalizedString
		/**
		 * 6 цифр
		 */
		zipDigitsOnly: () => LocalizedString
		/**
		 * Название должно состоять минимум из 2 букв.
		 */
		state_too_short: () => LocalizedString
		/**
		 * Номер должен содержать только цифры.
		 */
		invalid_phone: () => LocalizedString
		/**
		 * Возникла непредвиденная ошибка при сохранении
		 */
		saveError: () => LocalizedString
	}
	profile: {
		/**
		 * Товары, добавленные в список 'Избранное'
		 */
		wishlistTitle: () => LocalizedString
		/**
		 * Ваш список 'Избранное' пуст
		 */
		wishlistEmpty: () => LocalizedString
		/**
		 * Похоже, вы еще не добавили ни одного товара в свой список 'Избранное'. Начните просматривать и сохранять понравившиеся товары! Когда вы это сделаете, они появятся здесь.
		 */
		wishlistEmptyText: () => LocalizedString
		/**
		 * Ваша информация о доставке
		 */
		shippingTitle: () => LocalizedString
		/**
		 * Адрес доставки пока не указан.
		 */
		shippingNoYet: () => LocalizedString
		/**
		 * Вы еще не указали свой адрес доставки. Когда вы это сделаете, он появится здесь.
		 */
		shippingEmptyText: () => LocalizedString
		/**
		 * Ваши персональные данные
		 */
		personalInfoTitle: () => LocalizedString
		/**
		 * Данные о пользователе пока отсутствуют.
		 */
		personalInfoNoYet: () => LocalizedString
		/**
		 * Вы ещё не указали свои персональные данные. Когда вы это сделаете, они появятся здесь, и вы сможете их отредактировать.
		 */
		personalInfoEmptyText: () => LocalizedString
		/**
		 * Эл. почта / Логин
		 */
		email: () => LocalizedString
		/**
		 * Логин
		 */
		username: () => LocalizedString
		/**
		 * Имя
		 */
		firstName: () => LocalizedString
		/**
		 * Фамилия
		 */
		lastName: () => LocalizedString
		/**
		 * Дата рождения
		 */
		birthday: () => LocalizedString
		/**
		 * Телефон
		 */
		phone: () => LocalizedString
		/**
		 * Аватар профиля
		 */
		fileUpload: () => LocalizedString
		/**
		 * улица
		 */
		street: () => LocalizedString
		/**
		 * квартира
		 */
		house: () => LocalizedString
		/**
		 * дом
		 */
		apartment: () => LocalizedString
		/**
		 * город
		 */
		city: () => LocalizedString
		/**
		 * индекс
		 */
		zip: () => LocalizedString
		/**
		 * область
		 */
		region: () => LocalizedString
		/**
		 * страна
		 */
		state: () => LocalizedString
		/**
		 * Обновить адрес
		 */
		updateAddress: () => LocalizedString
		/**
		 * Добавить адрес
		 */
		addAddress: () => LocalizedString
		/**
		 * Обновить данные
		 */
		updateUserInfo: () => LocalizedString
		/**
		 * Добавить данные
		 */
		addUserInfo: () => LocalizedString
		/**
		 * Сохраняем Ваши данные...
		 */
		saving: () => LocalizedString
		/**
		 * Обновить Ваши данные
		 */
		updateData: () => LocalizedString
		/**
		 * Сохранить Ваши данные
		 */
		saveData: () => LocalizedString
		/**
		 * Ваши заказы
		 */
		ordersTitle: () => LocalizedString
		/**
		 * Заказов пока нет.
		 */
		ordersNoYet: () => LocalizedString
		/**
		 * Похоже, вы еще не размещали заказы. Когда вы это сделаете, они появятся здесь.
		 */
		ordersEmptyText: () => LocalizedString
		/**
		 * Номер не указан
		 */
		absentPhone: () => LocalizedString
		/**
		 * Информация отсутствует
		 */
		absentBirthday: () => LocalizedString
		emailChange: {
			/**
			 * Подтвердить
			 */
			btn: () => LocalizedString
			/**
			 * Высылаем Вам письмо ...
			 */
			loading: () => LocalizedString
			/**
			 * Смена эл. почты / логина
			 */
			title: () => LocalizedString
			/**
			 * Внимание!
			 */
			attention: () => LocalizedString
			/**
			 * Меняя адрес электронной почты, Вы меняете логин для авторизации в личный кабинет.
			 */
			infoBefore: () => LocalizedString
			/**
			 * После нажатия кнопки "Подтвердить" Вам будет выслано электронное письмо на указанный адрес. В этом письме вы должны
			 */
			infoAfterA: () => LocalizedString
			/**
			 * перейти по ссылке
			 */
			infoAfterB: () => LocalizedString
			/**
			 * для верификации вашего нового адреса.
			 */
			infoAfterC: () => LocalizedString
			/**
			 * После верификации вход в личный кабинет будет возможен уже только по новому электронному адресу.
			 */
			infoAfterII: () => LocalizedString
			/**
			 * Изменить эл.почту
			 */
			emailChangeBtn: () => LocalizedString
			/**
			 * Электронная почта
			 */
			email: () => LocalizedString
			/**
			 * ваша новая электронная почта
			 */
			emailPlaceholder: () => LocalizedString
			/**
			 * Пароль
			 */
			password: () => LocalizedString
			/**
			 * ваш текущий пароль
			 */
			passwordPlaceholder: () => LocalizedString
			/**
			 * На новый адрес отправлено письмо для верификации
			 */
			success: () => LocalizedString
			/**
			 * Ошибка при сохранении данных
			 */
			error: () => LocalizedString
			verification: {
				/**
				 * Процесс подтверждения изменения Вашего нового адреса электронной почты ...
				 */
				loading: () => LocalizedString
				/**
				 * 🎉 Адрес электронной почты успешно изменен!
				 */
				success: () => LocalizedString
				/**
				 * Пожалуйста, авторизуйтесь заново, используя теперь новый адрес электронной почты.
				 */
				loginAgain: () => LocalizedString
				/**
				 * Авторизоваться
				 */
				login: () => LocalizedString
				/**
				 * Ошибка!
				 */
				error: () => LocalizedString
				/**
				 * Токен недействителен или срок его действия истек.
				 */
				noToken: () => LocalizedString
			}
		}
	}
	successPage: {
		/**
		 * 🎉 Спасибо за покупку!
		 */
		thanx: () => LocalizedString
		/**
		 * Эта надпись показана только в тестовом режиме
		 */
		signTestOne: () => LocalizedString
		/**
		 * С сервера-эквайринга была получена криптограмма, платёжные данные были зашифрованы и переданы на сервер.
		 */
		signTestTwo: () => LocalizedString
		/**
		 * Ваш заказ
		 */
		order: () => LocalizedString
		/**
		 * Номер заказа:
		 */
		orderNo: () => LocalizedString
		/**
		 * Заказ успешно оформлен! Мы очень ценим Ваше сотрудничество и сообщим Вам о его отправке.
		 */
		messageSuccess: () => LocalizedString
		/**
		 * Просмотреть заказ
		 */
		orderView: () => LocalizedString
		/**
		 * Продолжить покупки
		 */
		'continue': () => LocalizedString
	}
	failedPage: {
		/**
		 * Ой! Ошибка оплаты.
		 */
		title: () => LocalizedString
		/**
		 * Что-то пошло не так при обработке вашего платежа. Не беспокойтесь — средства с вашей карты не были списаны.
		 */
		description: () => LocalizedString
		/**
		 * Попробовать снова
		 */
		tryAgain: () => LocalizedString
		/**
		 * Свяжитесь с нами
		 */
		contactUs: () => LocalizedString
		/**
		 * Поддержка — WhatsApp
		 */
		contactSupportWa: () => LocalizedString
		/**
		 * Поддержка — Email
		 */
		contactSupportEmail: () => LocalizedString
		/**
		 * Чат с поддержкой
		 */
		chatWithSupport: () => LocalizedString
		/**
		 * Ошибка оплаты заказа (Корзина: {cartCode})
		 */
		emailSubject: (arg: { cartCode: string }) => LocalizedString
	}
}

export type Formatters = {}
